# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

"""Accuracy tests for ``aten::_scaled_mm_v2``.

The operator is the recipe-driven spelling of the scaled matrix multiply:
``scale_a``/``scale_b`` arrive as lists, paired with ``recipe_a``/``recipe_b``
(``TensorWise`` / ``RowWise``) and, optionally, ``swizzle_a``/``swizzle_b``.

Only ``float8_e4m3fn`` operands with ``float32`` decoding scales are exercised,
matching what the upstream scaled GEMM kernels accept.  The reference is built
from the same operands in float32, so the comparison is deterministic.

``TensorWise`` / ``RowWise`` are the recipes the Triton kernel implements; the
block-wise recipes (``BlockWise1x128`` and friends) need a cublasLt that this
backend does not ship, so they are rejected rather than silently mishandled.
"""

import pytest
import torch

import flag_gems

from . import accuracy_utils as utils
from .conftest import QUICK_MODE

if QUICK_MODE:
    # Single small aligned shape for the quick smoke run.
    SCALED_MM_V2_SHAPES = [(64, 64, 128)]
else:
    # Mix of aligned (M,N,K) triples, including a non-16-multiple case to
    # exercise the tail handling in the fp8 GEMM.
    SCALED_MM_V2_SHAPES = [
        (64, 64, 128),
        (128, 256, 512),
        (100, 200, 64),
        (16, 32, 256),
    ]

# The upstream CUDA implementation rejects operands whose extents are not
# multiples of 16, so the cross-check only uses shapes it can serve.
ALIGNED_SHAPES = [
    shape for shape in SCALED_MM_V2_SHAPES if shape[1] % 16 == 0 and shape[2] % 16 == 0
]


def _cuda_fp8_available():
    if flag_gems.device != "cuda" or not torch.cuda.is_available():
        return False
    if not hasattr(torch, "float8_e4m3fn"):
        return False
    major, minor = torch.cuda.get_device_capability()
    return major * 10 + minor >= 89


# float8_e4m3fn operands are CUDA-only (sm89+); this operator has no
# float16/float32/bfloat16 form, so the dtype set is hardcoded.
def _dtype_cases():
    return [torch.float8_e4m3fn] if _cuda_fp8_available() else []


def _make_tensor(shape, dtype):
    base = torch.randn(shape, dtype=torch.float32, device=flag_gems.device) * 0.25
    try:
        return base.to(dtype)
    except RuntimeError as exc:
        pytest.skip(f"{dtype} is not supported on {flag_gems.device}: {exc}")


def _make_mat_b(k_size, n_size, dtype):
    """Build ``mat_b`` in the transposed (column major) layout the kernel wants.

    The kernel contracts along the leading dimension and walks columns with
    unit stride, so the values are materialised as ``(N, K)`` and swapped,
    leaving ``stride(0) == 1``.
    """
    base = torch.randn((n_size, k_size), dtype=torch.float32, device=flag_gems.device)
    return (base * 0.25).to(dtype).transpose(0, 1)


def _make_scales(m_size, n_size, mode):
    """Build the ``(scale_a, scale_b)`` pair for one of the two recipes."""
    if mode == "tensorwise":
        return (
            torch.full((1,), 0.75, device=flag_gems.device),
            torch.full((1,), 1.25, device=flag_gems.device),
        )

    scale_a = torch.linspace(0.75, 1.25, m_size, device=flag_gems.device)
    scale_b = torch.linspace(1.25, 0.75, n_size, device=flag_gems.device)
    return scale_a.reshape(m_size, 1), scale_b.reshape(1, n_size)


def _reference(mat_a, mat_b, scale_a, scale_b, bias, out_dtype):
    """Reference GEMM, computed on the CPU in float32.

    ``scale_a`` carries one factor per row of the product and ``scale_b`` one
    per column, which is what ``RowWise`` means for the two operands.
    """
    ref = mat_a.detach().cpu().float().mm(mat_b.detach().cpu().float())
    ref = ref * scale_a.detach().cpu().float().reshape(-1).unsqueeze(1)
    ref = ref * scale_b.detach().cpu().float().reshape(-1).unsqueeze(0)
    if bias is not None:
        ref = ref + bias.detach().cpu().float().reshape(1, -1)
    return ref.to(out_dtype).float()


def _run(mat_a, mat_b, scale_a, scale_b, bias, out_dtype, recipe_a, recipe_b, op=None):
    if op is None:
        op = torch._scaled_mm_v2
    return op(
        mat_a,
        mat_b,
        [scale_a],
        [recipe_a],
        [0],
        [scale_b],
        [recipe_b],
        [0],
        bias,
        out_dtype,
        [],
        False,
    )


@pytest.mark.scaled_mm_v2
@pytest.mark.parametrize("scale_mode,recipe", [("tensorwise", 0), ("rowwise", 1)])
@pytest.mark.parametrize("M, N, K", SCALED_MM_V2_SHAPES)
@pytest.mark.parametrize("dtype", _dtype_cases())
def test_scaled_mm_v2(M, N, K, dtype, scale_mode, recipe):
    mat_a = _make_tensor((M, K), dtype)
    mat_b = _make_mat_b(K, N, dtype)
    scale_a, scale_b = _make_scales(M, N, scale_mode)

    ref = _reference(mat_a, mat_b, scale_a, scale_b, None, torch.bfloat16)
    res = _run(
        mat_a,
        mat_b,
        scale_a,
        scale_b,
        None,
        torch.bfloat16,
        recipe,
        recipe,
        op=flag_gems._scaled_mm_v2,
    )

    assert res.shape == (M, N)
    assert res.dtype == torch.bfloat16
    # fp8 operands accumulate in float32 but the reference rounds to bf16, so
    # the comparison tolerates the ~1e-2 resolution bf16 carries at the
    # magnitudes this GEMM produces; ``reduce_dim=K`` scales atol with the
    # contraction length the accumulation runs over.
    ref = ref if utils.TO_CPU else ref.to(flag_gems.device)
    utils.gems_assert_close(res, ref, torch.bfloat16, reduce_dim=K)


@pytest.mark.scaled_mm_v2
@pytest.mark.parametrize("out_dtype", [torch.float32, torch.float16])
@pytest.mark.parametrize("dtype", _dtype_cases())
def test_scaled_mm_v2_bias(dtype, out_dtype):
    M, N, K = SCALED_MM_V2_SHAPES[0]
    mat_a = _make_tensor((M, K), dtype)
    mat_b = _make_mat_b(K, N, dtype)
    scale_a, scale_b = _make_scales(M, N, "rowwise")
    bias = torch.randn((N,), dtype=out_dtype, device=flag_gems.device)

    ref = _reference(mat_a, mat_b, scale_a, scale_b, bias, out_dtype)
    res = _run(
        mat_a,
        mat_b,
        scale_a,
        scale_b,
        bias,
        out_dtype,
        1,
        1,
        op=flag_gems._scaled_mm_v2,
    )

    assert res.shape == (M, N)
    assert res.dtype == out_dtype
    ref = ref if utils.TO_CPU else ref.to(flag_gems.device)
    utils.gems_assert_close(res, ref, out_dtype, reduce_dim=K)


@pytest.mark.scaled_mm_v2
@pytest.mark.parametrize("scale_mode,recipe", [("tensorwise", 0), ("rowwise", 1)])
@pytest.mark.parametrize("M, N, K", ALIGNED_SHAPES)
@pytest.mark.parametrize("dtype", _dtype_cases())
def test_scaled_mm_v2_vs_torch(M, N, K, dtype, scale_mode, recipe):
    """Cross-check the Triton kernel against the upstream CUDA implementation.

    Only the recipes the backend's cublasLt can serve are compared; the
    upstream call is skipped rather than failing when it is unavailable.
    """
    mat_a = _make_tensor((M, K), dtype)
    mat_b = _make_mat_b(K, N, dtype)
    scale_a, scale_b = _make_scales(M, N, scale_mode)

    try:
        ref = _run(mat_a, mat_b, scale_a, scale_b, None, torch.bfloat16, recipe, recipe)
    except (AttributeError, RuntimeError, NotImplementedError, ValueError) as exc:
        # AttributeError: torch builds that predate _scaled_mm_v2 (no torch._scaled_mm_v2).
        pytest.skip(f"upstream _scaled_mm_v2 cannot serve this case: {exc}")

    res = _run(
        mat_a,
        mat_b,
        scale_a,
        scale_b,
        None,
        torch.bfloat16,
        recipe,
        recipe,
        op=flag_gems._scaled_mm_v2,
    )

    ref = ref if utils.TO_CPU else ref.to(flag_gems.device)
    utils.gems_assert_close(res, ref, torch.bfloat16, reduce_dim=K)
