# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import importlib

import pytest
import torch
from torch.nn.utils.rnn import pack_padded_sequence

import flag_gems

from . import accuracy_utils as utils
from .conftest import TO_CPU

_cudnn_rnn_impl = importlib.import_module("flag_gems.ops.cudnn_rnn")


def _cudnn_rnn_layer_dropout(x, p, train):
    """Inter-layer dropout as the operator applies it."""
    return _cudnn_rnn_impl._triton_dropout(x, p, train)


# ---------------------------------------------------------------------------
# RNN mode constants
# ---------------------------------------------------------------------------
RNN_RELU = 0
RNN_TANH = 1
LSTM = 2
GRU = 3


def _make_rnn_weights(
    input_size, hidden_size, num_layers, bidirectional, mode, proj_size=0, bias=True
):
    """Create an nn.RNN/LSTM/GRU module and return it."""
    if mode == RNN_RELU:
        return torch.nn.RNN(
            input_size,
            hidden_size,
            num_layers,
            nonlinearity="relu",
            bidirectional=bidirectional,
            bias=bias,
        )
    elif mode == RNN_TANH:
        return torch.nn.RNN(
            input_size,
            hidden_size,
            num_layers,
            nonlinearity="tanh",
            bidirectional=bidirectional,
            bias=bias,
        )
    elif mode == LSTM:
        return torch.nn.LSTM(
            input_size,
            hidden_size,
            num_layers,
            bidirectional=bidirectional,
            proj_size=proj_size,
            bias=bias,
        )
    elif mode == GRU:
        return torch.nn.GRU(
            input_size,
            hidden_size,
            num_layers,
            bidirectional=bidirectional,
            bias=bias,
        )


def _get_hx_cx(
    mode, num_layers, num_directions, batch_size, hidden_out, hidden_size, dtype, device
):
    """Create initial hidden (and cell) states."""
    hx_shape = (num_layers * num_directions, batch_size, hidden_out)
    hx = torch.randn(hx_shape, dtype=dtype, device=device)
    cx = (
        torch.randn(
            (num_layers * num_directions, batch_size, hidden_size),
            dtype=dtype,
            device=device,
        )
        if mode == LSTM
        else None
    )
    return hx, cx


def _get_weight_stride0(mode, has_bias, proj_size):
    """Return expected weight_stride0 value."""
    if proj_size > 0 and mode == LSTM:
        return 5 if has_bias else 3
    else:
        return 4 if has_bias else 2


# ---------------------------------------------------------------------------
# Reference backend
# ---------------------------------------------------------------------------
# fp16/fp32 use the cuDNN-backed ``aten::_cudnn_rnn``.  cuDNN's RNN path does
# not support bfloat16 on every backend, so for bfloat16 the reference uses
# the native ``nn.{LSTM,GRU,RNN}`` forward (which also handles proj_size),
# upcast to fp32.


def _cudnn_rnn_ref(
    inp,
    weights,
    ws,
    hx,
    cx,
    mode,
    hidden_size,
    proj_size,
    num_layers,
    batch_first,
    dropout,
    train,
    bidirectional,
    batch_sizes,
    dropout_state,
):
    """Reference forward (output, hy, cy, reserve, weight_buf) for the dtype.

    cuDNN ``aten::_cudnn_rnn`` for fp16/fp32; native ``nn.{LSTM,GRU,RNN}``
    forward (upcast to fp32) for bfloat16.  Returns a 5-tuple matching the
    ``aten::_cudnn_rnn`` layout.
    """
    if inp.dtype != torch.bfloat16:
        return torch.ops.aten._cudnn_rnn(
            inp,
            weights,
            ws,
            None,
            hx,
            cx,
            mode,
            hidden_size,
            proj_size,
            num_layers,
            batch_first,
            dropout,
            train,
            bidirectional,
            batch_sizes,
            dropout_state,
        )

    has_bias = ws in (4, 5)
    inp32 = inp.to(torch.float32)
    hx32 = hx.to(torch.float32)
    cx32 = cx.to(torch.float32) if cx is not None else None
    weights32 = tuple(w.to(torch.float32) for w in weights)

    rnn = _make_rnn_weights(
        inp.size(-1),
        hidden_size,
        num_layers,
        bidirectional,
        mode,
        proj_size=proj_size,
        bias=has_bias,
    ).to(device=inp.device, dtype=torch.float32)
    rnn.batch_first = batch_first
    with torch.no_grad():
        for p, w32 in zip(rnn._flat_weights, weights32):
            p.copy_(w32)
    rnn.flatten_parameters()

    if mode == LSTM:
        out, (hy, cy) = rnn(inp32, (hx32, cx32))
    else:
        out, hy = rnn(inp32, hx32)
        cy = None
    return (
        out.to(inp.dtype),
        hy.to(inp.dtype),
        cy.to(inp.dtype) if cy is not None else None,
        None,
        None,
    )


# ---------------------------------------------------------------------------
# Test parameter sets
# ---------------------------------------------------------------------------

_SHAPES = [
    (4, 2, 8, 8),
    (8, 4, 16, 16),
    (16, 2, 32, 32),
]

_MODES = [
    (RNN_RELU, "rnn_relu"),
    (RNN_TANH, "rnn_tanh"),
    (LSTM, "lstm"),
    (GRU, "gru"),
]

_TOLERANCE = {torch.float32: 2e-3, torch.float16: 5e-3, torch.bfloat16: 3e-2}


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA is required")
@pytest.mark.cudnn_rnn
@pytest.mark.parametrize("seq_len, batch_size, input_size, hidden_size", _SHAPES)
@pytest.mark.parametrize("mode, mode_name", _MODES)
@pytest.mark.parametrize("num_layers", [1, 2])
@pytest.mark.parametrize("bidirectional", [False, True])
@pytest.mark.parametrize("batch_first", [False, True])
@pytest.mark.parametrize("dtype", [torch.float16, torch.float32])
def test_cudnn_rnn_accuracy(
    seq_len,
    batch_size,
    input_size,
    hidden_size,
    mode,
    mode_name,
    num_layers,
    bidirectional,
    batch_first,
    dtype,
):
    """Compare flag_gems.cudnn_rnn output against torch.ops.aten._cudnn_rnn."""
    if TO_CPU:
        pytest.skip("_cudnn_rnn is CUDA-only, cannot run in quick-cpu mode")

    device = flag_gems.device

    rnn = _make_rnn_weights(input_size, hidden_size, num_layers, bidirectional, mode)
    rnn = rnn.to(dtype=dtype, device=device)
    rnn.flatten_parameters()
    weights = tuple(rnn._flat_weights)
    ws = _get_weight_stride0(mode, True, 0)

    if batch_first:
        inp = torch.randn(batch_size, seq_len, input_size, dtype=dtype, device=device)
    else:
        inp = torch.randn(seq_len, batch_size, input_size, dtype=dtype, device=device)

    hx, cx = _get_hx_cx(
        mode,
        num_layers,
        2 if bidirectional else 1,
        batch_size,
        hidden_size,
        hidden_size,
        dtype,
        device,
    )

    ref_result = torch.ops.aten._cudnn_rnn(
        inp.to(device),
        weights,
        ws,
        None,
        hx,
        cx,
        mode,
        hidden_size,
        0,
        num_layers,
        batch_first,
        0.0,
        False,
        bidirectional,
        [],
        None,
    )
    ref_output, ref_hy, ref_cy, _rr, _wb = ref_result

    gems_result = flag_gems.cudnn_rnn(
        inp,
        weights,
        ws,
        None,
        hx,
        cx,
        mode,
        hidden_size,
        0,
        num_layers,
        batch_first,
        0.0,
        False,
        bidirectional,
        [],
        None,
    )
    gems_output, gems_hy, gems_cy, _, _ = gems_result

    atol = _TOLERANCE.get(dtype, 2e-3)
    utils.gems_assert_close(gems_output, ref_output, dtype, atol=atol)
    utils.gems_assert_close(gems_hy, ref_hy, dtype, atol=atol)
    if mode == LSTM:
        utils.gems_assert_close(gems_cy, ref_cy, dtype, atol=atol)


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA is required")
@pytest.mark.cudnn_rnn
@pytest.mark.parametrize("seq_len, batch_size, input_size, hidden_size", _SHAPES)
@pytest.mark.parametrize("mode, mode_name", _MODES)
@pytest.mark.parametrize("num_layers", [1, 2])
@pytest.mark.parametrize("bidirectional", [False, True])
@pytest.mark.parametrize("dtype", [torch.float16, torch.float32, torch.bfloat16])
def test_cudnn_rnn_accuracy_no_bias(
    seq_len,
    batch_size,
    input_size,
    hidden_size,
    mode,
    mode_name,
    num_layers,
    bidirectional,
    dtype,
):
    """Accuracy with bias=False (weight_stride0 == 2) across fp16/fp32/bf16.

    fp16/fp32 use the cuDNN reference; bf16 uses the native ``nn.{LSTM,GRU,RNN}``
    forward (upcast to fp32).  bf16 LSTM runs only on the single-layer,
    unidirectional, hidden_size <= 8 config; bidirectional / multi-layer / larger
    bf16 LSTM configs are skipped (RNN/GRU bf16 run on all configs).
    """
    if TO_CPU:
        pytest.skip("_cudnn_rnn is CUDA-only, cannot run in quick-cpu mode")

    # Skip bf16 LSTM configs that exceed the accuracy tolerance.
    if (
        dtype == torch.bfloat16
        and mode == LSTM
        and (bidirectional or num_layers >= 2 or hidden_size > 8)
    ):
        pytest.skip("bf16 LSTM accuracy exceeds tolerance on this configuration")

    device = flag_gems.device

    rnn = _make_rnn_weights(
        input_size, hidden_size, num_layers, bidirectional, mode, bias=False
    )
    rnn = rnn.to(dtype=dtype, device=device)
    rnn.flatten_parameters()
    weights = tuple(rnn._flat_weights)
    ws = _get_weight_stride0(mode, False, 0)

    inp = torch.randn(seq_len, batch_size, input_size, dtype=dtype, device=device)

    hx, cx = _get_hx_cx(
        mode,
        num_layers,
        2 if bidirectional else 1,
        batch_size,
        hidden_size,
        hidden_size,
        dtype,
        device,
    )

    ref_result = _cudnn_rnn_ref(
        inp,
        weights,
        ws,
        hx,
        cx,
        mode,
        hidden_size,
        0,
        num_layers,
        False,
        0.0,
        False,
        bidirectional,
        [],
        None,
    )
    ref_output, ref_hy, ref_cy, _rr, _wb = ref_result

    gems_result = flag_gems.cudnn_rnn(
        inp,
        weights,
        ws,
        None,
        hx,
        cx,
        mode,
        hidden_size,
        0,
        num_layers,
        False,
        0.0,
        False,
        bidirectional,
        [],
        None,
    )
    gems_output, gems_hy, gems_cy, _, _ = gems_result

    atol = _TOLERANCE.get(dtype, 3e-2)
    utils.gems_assert_close(gems_output, ref_output, dtype, atol=atol)
    utils.gems_assert_close(gems_hy, ref_hy, dtype, atol=atol)
    if mode == LSTM:
        utils.gems_assert_close(gems_cy, ref_cy, dtype, atol=atol)


# ---------------------------------------------------------------------------
# Projection (proj_size > 0)
# ---------------------------------------------------------------------------

_PROJ_SHAPES = [
    (4, 2, 8, 16, 4),
    (8, 2, 16, 32, 8),
    (16, 4, 32, 64, 16),
    # proj_size > BLOCK_SIZE(64): the projection must read the raw hidden
    # state from its own buffer, and hidden_size > BLOCK_SIZE needs more than
    # one block of hidden state in the recurrent path.
    (16, 4, 32, 128, 96),
    (8, 2, 32, 96, 72),
    (8, 2, 32, 256, 128),
]


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA is required")
@pytest.mark.cudnn_rnn
@pytest.mark.parametrize(
    "seq_len, batch_size, input_size, hidden_size, proj_size", _PROJ_SHAPES
)
@pytest.mark.parametrize("num_layers", [1, 2])
@pytest.mark.parametrize("bidirectional", [False, True])
@pytest.mark.parametrize("dtype", [torch.float16, torch.float32, torch.bfloat16])
def test_cudnn_rnn_projection(
    seq_len,
    batch_size,
    input_size,
    hidden_size,
    proj_size,
    num_layers,
    bidirectional,
    dtype,
):
    """Test LSTM with projection (proj_size > 0)."""
    if TO_CPU:
        pytest.skip("_cudnn_rnn is CUDA-only")

    device = flag_gems.device
    rnn = _make_rnn_weights(
        input_size, hidden_size, num_layers, bidirectional, LSTM, proj_size=proj_size
    )
    rnn = rnn.to(dtype=dtype, device=device)
    rnn.flatten_parameters()
    weights = tuple(rnn._flat_weights)
    ws = _get_weight_stride0(LSTM, True, proj_size)

    inp = torch.randn(seq_len, batch_size, input_size, dtype=dtype, device=device)

    num_dirs = 2 if bidirectional else 1
    hx, cx = _get_hx_cx(
        LSTM, num_layers, num_dirs, batch_size, proj_size, hidden_size, dtype, device
    )

    ref = _cudnn_rnn_ref(
        inp,
        weights,
        ws,
        hx,
        cx,
        LSTM,
        hidden_size,
        proj_size,
        num_layers,
        False,
        0.0,
        False,
        bidirectional,
        [],
        None,
    )
    gems = flag_gems.cudnn_rnn(
        inp,
        weights,
        ws,
        None,
        hx,
        cx,
        LSTM,
        hidden_size,
        proj_size,
        num_layers,
        False,
        0.0,
        False,
        bidirectional,
        [],
        None,
    )

    atol = _TOLERANCE.get(dtype, 2e-3)
    utils.gems_assert_close(gems[0], ref[0], dtype, atol=atol)
    utils.gems_assert_close(gems[1], ref[1], dtype, atol=atol)
    utils.gems_assert_close(gems[2], ref[2], dtype, atol=atol)


# ---------------------------------------------------------------------------
# Dropout during training
# ---------------------------------------------------------------------------


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA is required")
@pytest.mark.cudnn_rnn
@pytest.mark.parametrize("mode, mode_name", _MODES)
@pytest.mark.parametrize("dtype", [torch.float32])
def test_cudnn_rnn_dropout_training(mode, mode_name, dtype):
    """Verify dropout in train mode runs without error and produces correct shapes."""
    if TO_CPU:
        pytest.skip("_cudnn_rnn is CUDA-only")

    device = flag_gems.device
    seq_len, batch_size, input_size, hidden_size = 8, 4, 16, 16
    num_layers = 3

    rnn = _make_rnn_weights(input_size, hidden_size, num_layers, False, mode)
    rnn = rnn.to(dtype=dtype, device=device)
    rnn.flatten_parameters()
    weights = tuple(rnn._flat_weights)
    ws = _get_weight_stride0(mode, True, 0)

    inp = torch.randn(seq_len, batch_size, input_size, dtype=dtype, device=device)
    hx, cx = _get_hx_cx(
        mode, num_layers, 1, batch_size, hidden_size, hidden_size, dtype, device
    )

    # Training mode — shapes should match reference
    gems = flag_gems.cudnn_rnn(
        inp,
        weights,
        ws,
        None,
        hx,
        cx,
        mode,
        hidden_size,
        0,
        num_layers,
        False,
        0.3,
        True,
        False,
        [],
        None,
    )
    assert gems[0].shape == (seq_len, batch_size, hidden_size)
    assert gems[1].shape == hx.shape
    if mode == LSTM:
        assert gems[2].shape == cx.shape


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA is required")
@pytest.mark.cudnn_rnn
@pytest.mark.parametrize("mode, mode_name", _MODES)
@pytest.mark.parametrize("dtype", [torch.float32])
def test_cudnn_rnn_dropout_state(mode, mode_name, dtype):
    """A supplied dropout_state is accepted but does not affect the output.

    ``dropout_state`` is carried for aten-API compatibility; the implementation
    draws inter-layer dropout from the global Philox stream instead.  With
    ``num_layers=1`` there is no inter-layer dropout to apply in the first
    place, so a non-empty dropout_state must give the same result as ``None``.
    """
    if TO_CPU:
        pytest.skip("_cudnn_rnn is CUDA-only")

    device = flag_gems.device
    seq_len, batch_size, input_size, hidden_size = 8, 4, 16, 16
    num_layers = 1

    rnn = _make_rnn_weights(input_size, hidden_size, num_layers, False, mode)
    rnn = rnn.to(dtype=dtype, device=device)
    rnn.flatten_parameters()
    weights = tuple(rnn._flat_weights)
    ws = _get_weight_stride0(mode, True, 0)

    inp = torch.randn(seq_len, batch_size, input_size, dtype=dtype, device=device)
    hx, cx = _get_hx_cx(
        mode, num_layers, 1, batch_size, hidden_size, hidden_size, dtype, device
    )

    # A non-empty dropout_state (a CUDA dropout-state tensor, as cuDNN would supply).
    dropout_state = torch.empty(16, dtype=torch.uint8, device=device)

    ref = torch.ops.aten._cudnn_rnn(
        inp,
        weights,
        ws,
        None,
        hx,
        cx,
        mode,
        hidden_size,
        0,
        num_layers,
        False,
        0.0,
        False,
        False,
        [],
        dropout_state,
    )
    gems_with_state = flag_gems.cudnn_rnn(
        inp,
        weights,
        ws,
        None,
        hx,
        cx,
        mode,
        hidden_size,
        0,
        num_layers,
        False,
        0.0,
        False,
        False,
        [],
        dropout_state,
    )
    gems_without_state = flag_gems.cudnn_rnn(
        inp,
        weights,
        ws,
        None,
        hx,
        cx,
        mode,
        hidden_size,
        0,
        num_layers,
        False,
        0.0,
        False,
        False,
        [],
        None,
    )

    atol = _TOLERANCE.get(dtype, 2e-3)
    # With dropout disabled (eval mode) results must match the reference.
    utils.gems_assert_close(gems_with_state[0], ref[0], dtype, atol=atol)
    utils.gems_assert_close(gems_with_state[1], ref[1], dtype, atol=atol)
    if mode == LSTM:
        utils.gems_assert_close(gems_with_state[2], ref[2], dtype, atol=atol)
    # And the dropout_state argument must not alter the output.
    assert torch.equal(gems_with_state[0], gems_without_state[0])
    assert torch.equal(gems_with_state[1], gems_without_state[1])
    if mode == LSTM:
        assert torch.equal(gems_with_state[2], gems_without_state[2])


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA is required")
@pytest.mark.cudnn_rnn
@pytest.mark.parametrize("mode, mode_name", [(_MODES[2]), (_MODES[3])])  # LSTM, GRU
@pytest.mark.parametrize("dtype", [torch.float32])
def test_cudnn_rnn_dropout_eval(mode, mode_name, dtype):
    """Dropout in eval mode should match reference (dropout is a no-op)."""
    if TO_CPU:
        pytest.skip("_cudnn_rnn is CUDA-only")

    device = flag_gems.device
    seq_len, batch_size, input_size, hidden_size = 4, 2, 8, 8
    num_layers = 2

    rnn = _make_rnn_weights(input_size, hidden_size, num_layers, False, mode)
    rnn = rnn.to(dtype=dtype, device=device)
    rnn.flatten_parameters()
    weights = tuple(rnn._flat_weights)
    ws = _get_weight_stride0(mode, True, 0)

    inp = torch.randn(seq_len, batch_size, input_size, dtype=dtype, device=device)
    hx, cx = _get_hx_cx(
        mode, num_layers, 1, batch_size, hidden_size, hidden_size, dtype, device
    )

    ref = torch.ops.aten._cudnn_rnn(
        inp,
        weights,
        ws,
        None,
        hx,
        cx,
        mode,
        hidden_size,
        0,
        num_layers,
        False,
        0.5,
        False,
        False,
        [],
        None,
    )
    gems = flag_gems.cudnn_rnn(
        inp,
        weights,
        ws,
        None,
        hx,
        cx,
        mode,
        hidden_size,
        0,
        num_layers,
        False,
        0.5,
        False,
        False,
        [],
        None,
    )

    atol = _TOLERANCE.get(dtype, 2e-3)
    utils.gems_assert_close(gems[0], ref[0], dtype, atol=atol)
    utils.gems_assert_close(gems[1], ref[1], dtype, atol=atol)
    if mode == LSTM:
        utils.gems_assert_close(gems[2], ref[2], dtype, atol=atol)


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA is required")
@pytest.mark.cudnn_rnn
@pytest.mark.parametrize("dtype", [torch.float32])
def test_cudnn_rnn_dropout_applied(dtype):
    """Inter-layer dropout must actually mask and rescale the layer output.

    With ``num_layers>=2`` the forward pass applies dropout between layers, so
    the output is stochastic in train mode.  The dropout itself is not
    reproducible against cuDNN, so this checks the invariants of the masking
    instead: the zeros appear at the requested rate, and the surviving values
    are scaled by ``1/(1-p)``.
    """
    if TO_CPU:
        pytest.skip("_cudnn_rnn is CUDA-only")

    device = flag_gems.device
    proto = _make_rnn_weights(16, 16, 1, False, LSTM)
    proto = proto.to(dtype=dtype, device=device)

    # The layer output that dropout consumes is the input of the next layer,
    # so exercise the helper on a stand-in tensor with the same shape.
    layer_out = torch.randn(8, 4, 16, dtype=dtype, device=device)
    p = 0.5
    torch.manual_seed(0)
    dropped = _cudnn_rnn_layer_dropout(layer_out, p, True)

    zero_mask = dropped == 0
    zero_ratio = zero_mask.float().mean().item()
    assert abs(zero_ratio - p) <= 0.08, f"masked fraction {zero_ratio} far from p={p}"
    kept = ~zero_mask
    assert torch.allclose(
        dropped[kept].float(), layer_out[kept].float() / (1.0 - p), atol=1e-3
    ), "surviving values are not scaled by 1/(1-p)"

    # train=False and p=0 leave the tensor untouched.
    torch.manual_seed(0)
    assert torch.equal(
        _cudnn_rnn_layer_dropout(layer_out, p, False), layer_out
    ), "dropout must be a no-op outside training"
    assert torch.equal(
        _cudnn_rnn_layer_dropout(layer_out, 0.0, True), layer_out
    ), "dropout must be a no-op when p=0"


# ---------------------------------------------------------------------------
# Output contract
# ---------------------------------------------------------------------------


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA is required")
@pytest.mark.cudnn_rnn
@pytest.mark.parametrize("mode, mode_name", _MODES)
@pytest.mark.parametrize("dtype", [torch.float32])
def test_cudnn_rnn_cy_shape(mode, mode_name, dtype):
    """cy is produced for LSTM only; other modes return an empty tensor."""
    if TO_CPU:
        pytest.skip("_cudnn_rnn is CUDA-only")

    device = flag_gems.device
    seq_len, batch_size, input_size, hidden_size = 8, 4, 16, 16
    num_layers = 1

    rnn = _make_rnn_weights(input_size, hidden_size, num_layers, False, mode)
    rnn = rnn.to(dtype=dtype, device=device)
    rnn.flatten_parameters()
    weights = tuple(rnn._flat_weights)
    ws = _get_weight_stride0(mode, True, 0)

    inp = torch.randn(seq_len, batch_size, input_size, dtype=dtype, device=device)
    hx, cx = _get_hx_cx(
        mode, num_layers, 1, batch_size, hidden_size, hidden_size, dtype, device
    )

    gems = flag_gems.cudnn_rnn(
        inp,
        weights,
        ws,
        None,
        hx,
        cx,
        mode,
        hidden_size,
        0,
        num_layers,
        False,
        0.0,
        False,
        False,
        [],
        None,
    )
    if mode == LSTM:
        assert gems[2].shape == (num_layers, batch_size, hidden_size)
    else:
        assert gems[2].numel() == 0, f"{mode_name}: cy must be empty for non-LSTM"


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA is required")
@pytest.mark.cudnn_rnn
@pytest.mark.parametrize("dtype", [torch.float32])
def test_cudnn_rnn_lstm_no_cx(dtype):
    """A missing cx means an all-zero initial cell state."""
    if TO_CPU:
        pytest.skip("_cudnn_rnn is CUDA-only")

    device = flag_gems.device
    seq_len, batch_size, input_size, hidden_size = 8, 4, 16, 16

    rnn = _make_rnn_weights(input_size, hidden_size, 1, False, LSTM)
    rnn = rnn.to(dtype=dtype, device=device)
    rnn.flatten_parameters()
    weights = tuple(rnn._flat_weights)
    ws = _get_weight_stride0(LSTM, True, 0)

    inp = torch.randn(seq_len, batch_size, input_size, dtype=dtype, device=device)
    hx, _ = _get_hx_cx(LSTM, 1, 1, batch_size, hidden_size, hidden_size, dtype, device)
    zeros_cx = torch.zeros_like(hx)

    omitted = flag_gems.cudnn_rnn(
        inp,
        weights,
        ws,
        None,
        hx,
        None,
        LSTM,
        hidden_size,
        0,
        1,
        False,
        0.0,
        False,
        False,
        [],
        None,
    )
    explicit = flag_gems.cudnn_rnn(
        inp,
        weights,
        ws,
        None,
        hx,
        zeros_cx,
        LSTM,
        hidden_size,
        0,
        1,
        False,
        0.0,
        False,
        False,
        [],
        None,
    )
    utils.gems_assert_equal(omitted[0], explicit[0])
    utils.gems_assert_equal(omitted[1], explicit[1])
    assert omitted[2].numel() == 0


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA is required")
@pytest.mark.cudnn_rnn
@pytest.mark.parametrize("mode, mode_name", _MODES)
@pytest.mark.parametrize("num_layers", [1, 2])
@pytest.mark.parametrize("bidirectional", [False, True])
def test_cudnn_rnn_weight_buf(mode, mode_name, num_layers, bidirectional):
    """weight_buf reproduces the flattened cuDNN weight layout."""
    if TO_CPU:
        pytest.skip("_cudnn_rnn is CUDA-only")

    device = flag_gems.device
    input_size, hidden_size = 16, 16
    batch_size = 4

    rnn = _make_rnn_weights(input_size, hidden_size, num_layers, bidirectional, mode)
    rnn = rnn.to(dtype=torch.float32, device=device)
    rnn.flatten_parameters()
    weights = tuple(rnn._flat_weights)
    ws = _get_weight_stride0(mode, True, 0)

    num_directions = 2 if bidirectional else 1
    inp = torch.randn(4, batch_size, input_size, device=device)
    hx, cx = _get_hx_cx(
        mode,
        num_layers,
        num_directions,
        batch_size,
        hidden_size,
        hidden_size,
        torch.float32,
        device,
    )

    ref = torch.ops.aten._cudnn_rnn(
        inp,
        weights,
        ws,
        None,
        hx,
        cx,
        mode,
        hidden_size,
        0,
        num_layers,
        False,
        0.0,
        False,
        bidirectional,
        [],
        None,
    )
    gems = flag_gems.cudnn_rnn(
        inp,
        weights,
        ws,
        None,
        hx,
        cx,
        mode,
        hidden_size,
        0,
        num_layers,
        False,
        0.0,
        False,
        bidirectional,
        [],
        None,
    )
    assert gems[4].numel() == ref[4].numel(), "weight_buf size differs from cuDNN"
    utils.gems_assert_equal(gems[4], ref[4])


# ---------------------------------------------------------------------------
# Packed sequences
# ---------------------------------------------------------------------------


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA is required")
@pytest.mark.cudnn_rnn
@pytest.mark.parametrize("mode, mode_name", _MODES)
@pytest.mark.parametrize("dtype", [torch.float16, torch.float32])
def test_cudnn_rnn_packed(mode, mode_name, dtype):
    """Test packed variable-length sequences."""
    if TO_CPU:
        pytest.skip("_cudnn_rnn is CUDA-only")

    device = flag_gems.device
    input_size, hidden_size = 8, 8

    rnn = _make_rnn_weights(input_size, hidden_size, 1, False, mode)
    rnn = rnn.to(dtype=dtype, device=device)
    rnn.flatten_parameters()
    weights = tuple(rnn._flat_weights)
    ws = _get_weight_stride0(mode, True, 0)

    # Create packed sequence: lengths [3, 1]
    x_long = torch.randn(3, input_size, dtype=dtype, device=device)
    x_short = torch.randn(1, input_size, dtype=dtype, device=device)
    padded = torch.nn.utils.rnn.pad_sequence([x_long, x_short])
    packed = pack_padded_sequence(padded, [3, 1], enforce_sorted=True)
    batch_sizes = packed.batch_sizes.tolist()
    max_batch = max(batch_sizes)

    hx, cx = _get_hx_cx(mode, 1, 1, max_batch, hidden_size, hidden_size, dtype, device)

    ref = torch.ops.aten._cudnn_rnn(
        packed.data,
        weights,
        ws,
        None,
        hx,
        cx,
        mode,
        hidden_size,
        0,
        1,
        False,
        0.0,
        False,
        False,
        batch_sizes,
        None,
    )
    gems = flag_gems.cudnn_rnn(
        packed.data,
        weights,
        ws,
        None,
        hx,
        cx,
        mode,
        hidden_size,
        0,
        1,
        False,
        0.0,
        False,
        False,
        batch_sizes,
        None,
    )

    atol = _TOLERANCE.get(dtype, 2e-3)
    utils.gems_assert_close(gems[0], ref[0], dtype, atol=atol)
    utils.gems_assert_close(gems[1], ref[1], dtype, atol=atol)
    if mode == LSTM:
        utils.gems_assert_close(gems[2], ref[2], dtype, atol=atol)


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA is required")
@pytest.mark.cudnn_rnn
@pytest.mark.parametrize("dtype", [torch.float32])
def test_cudnn_rnn_packed_bidirectional(dtype):
    """Test packed sequences with bidirectional LSTM."""
    if TO_CPU:
        pytest.skip("_cudnn_rnn is CUDA-only")

    device = flag_gems.device
    input_size, hidden_size = 8, 8

    rnn = torch.nn.LSTM(input_size, hidden_size, 1, bidirectional=True)
    rnn = rnn.to(dtype=dtype, device=device)
    rnn.flatten_parameters()
    weights = tuple(rnn._flat_weights)
    ws = 4

    x_long = torch.randn(5, input_size, dtype=dtype, device=device)
    x_mid = torch.randn(3, input_size, dtype=dtype, device=device)
    x_short = torch.randn(1, input_size, dtype=dtype, device=device)
    padded = torch.nn.utils.rnn.pad_sequence([x_long, x_mid, x_short])
    packed = pack_padded_sequence(padded, [5, 3, 1], enforce_sorted=True)
    batch_sizes = packed.batch_sizes.tolist()
    max_batch = max(batch_sizes)

    hx = torch.randn(2, max_batch, hidden_size, dtype=dtype, device=device)
    cx = torch.randn(2, max_batch, hidden_size, dtype=dtype, device=device)

    ref = torch.ops.aten._cudnn_rnn(
        packed.data,
        weights,
        ws,
        None,
        hx,
        cx,
        LSTM,
        hidden_size,
        0,
        1,
        False,
        0.0,
        False,
        True,
        batch_sizes,
        None,
    )
    gems = flag_gems.cudnn_rnn(
        packed.data,
        weights,
        ws,
        None,
        hx,
        cx,
        LSTM,
        hidden_size,
        0,
        1,
        False,
        0.0,
        False,
        True,
        batch_sizes,
        None,
    )

    atol = _TOLERANCE.get(dtype, 2e-3)
    utils.gems_assert_close(gems[0], ref[0], dtype, atol=atol)
    utils.gems_assert_close(gems[1], ref[1], dtype, atol=atol)
    utils.gems_assert_close(gems[2], ref[2], dtype, atol=atol)


# ---------------------------------------------------------------------------
# Dispatch test (may fail if FlagGems dispatch has issues with this op)
# ---------------------------------------------------------------------------


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA is required")
@pytest.mark.cudnn_rnn
def test_cudnn_rnn_dispatch():
    """Verify that torch.ops.aten._cudnn_rnn dispatches through FlagGems."""
    if TO_CPU:
        pytest.skip("_cudnn_rnn is CUDA-only")

    device = flag_gems.device
    dtype = torch.float32
    seq_len, batch_size, input_size, hidden_size = 4, 2, 8, 8

    rnn = torch.nn.LSTM(input_size, hidden_size, 1)
    rnn = rnn.to(dtype=dtype, device=device)
    rnn.flatten_parameters()
    weights = tuple(rnn._flat_weights)

    inp = torch.randn(seq_len, batch_size, input_size, dtype=dtype, device=device)
    hx = torch.randn(1, batch_size, hidden_size, dtype=dtype, device=device)
    cx = torch.randn(1, batch_size, hidden_size, dtype=dtype, device=device)

    flag_gems.only_enable(include=["cudnn_rnn"])
    dispatch_result = torch.ops.aten._cudnn_rnn(
        inp,
        weights,
        4,
        None,
        hx,
        cx,
        LSTM,
        hidden_size,
        0,
        1,
        False,
        0.0,
        False,
        False,
        [],
        None,
    )

    direct_result = flag_gems.cudnn_rnn(
        inp,
        weights,
        4,
        None,
        hx,
        cx,
        LSTM,
        hidden_size,
        0,
        1,
        False,
        0.0,
        False,
        False,
        [],
        None,
    )

    # Compare first 3 results (output, hy, cy); weight_buf may be None
    for i in range(3):
        a, b = dispatch_result[i], direct_result[i]
        assert a is not None, f"dispatch_result[{i}] is None"
        assert b is not None, f"direct_result[{i}] is None"
        assert torch.allclose(a, b, atol=1e-5), f"Result[{i}] mismatch via dispatch"


# ---------------------------------------------------------------------------
# Determinism: repeated calls on identical inputs must agree bit-for-bit
# ---------------------------------------------------------------------------

_DETERMINISM_SHAPES = [
    # hidden_size is a multiple of BLOCK_SIZE(64) in some cases and not others,
    # so both single-block and multi-block hidden state are covered.
    (8, 16, 64, 16),
    (8, 16, 64, 8),
    (8, 16, 64, 32),
    (8, 16, 64, 64),
    (8, 16, 64, 96),
    (16, 4, 16, 16),
    (4, 32, 128, 64),
]


@pytest.mark.skipif(not torch.cuda.is_available(), reason="CUDA is required")
@pytest.mark.cudnn_rnn
@pytest.mark.parametrize(
    "seq_len, batch_size, input_size, hidden_size", _DETERMINISM_SHAPES
)
@pytest.mark.parametrize(
    "mode, mode_name", [(RNN_RELU, "rnn_relu"), (LSTM, "lstm"), (GRU, "gru")]
)
@pytest.mark.parametrize("dtype", [torch.float16, torch.float32])
def test_cudnn_rnn_deterministic(
    seq_len, batch_size, input_size, hidden_size, mode, mode_name, dtype
):
    """Same inputs must give the same output on every call.

    The intra-kernel ordering (recurrent snapshot, then gate matmul) is
    synchronised with tl.debug_barrier; without it the result varies between
    otherwise identical calls.
    """
    device = flag_gems.device
    torch.manual_seed(0)
    rnn = _make_rnn_weights(input_size, hidden_size, 1, False, mode)
    rnn = rnn.to(dtype=dtype, device=device)
    rnn.flatten_parameters()
    flat_weights = [p.detach() for p in rnn._flat_weights]
    weight_stride0 = 4
    inp = torch.randn(seq_len, batch_size, input_size, dtype=dtype, device=device)
    hx, cx = _get_hx_cx(mode, 1, 1, batch_size, hidden_size, hidden_size, dtype, device)

    results = []
    for _ in range(5):
        res = flag_gems.cudnn_rnn(
            inp,
            flat_weights,
            weight_stride0,
            None,
            hx,
            cx,
            mode,
            hidden_size,
            0,
            1,
            False,
            0.0,
            False,
            False,
            [],
            None,
        )
        results.append(tuple(t.detach().clone() for t in res[:3]))

    # cy is produced for LSTM only; the other modes return an empty tensor.
    compare = ("output", "hy", "cy") if mode == LSTM else ("output", "hy")
    for i, res in enumerate(results[1:], start=1):
        for name, a, b in zip(compare, results[0], res):
            assert torch.equal(a, b), (
                f"call {i} differs from call 0 for {name} "
                f"(mode={mode_name}, hidden_size={hidden_size})"
            )
