# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl
from torch import Tensor

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


def make_3d_for_bn(input: Tensor) -> Tensor:
    """
    Converts the input to a 3D view for batch normalization.

    Args:
        input: Input to render 3D.

    Returns:
        Input's 3D view.
    """
    if input.ndim == 2:
        input = input.unsqueeze(-1)

    elif input.ndim >= 4:
        input = input.flatten(2, -1)

    return input


# NOTE: This part of the kernel code is copied and modified
# from the https://github.com/BobMcDear/attorch codebase.


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("batch_norm"),
    key=["batch_dim", "spatial_dim"],
    restore_value=["running_mean_pointer", "running_var_pointer"],
)
@triton.heuristics(runtime.get_heuristic_config("batch_norm"))
@triton.jit
def batch_norm_with_update_kernel(
    input_pointer,
    weight_pointer,
    bias_pointer,
    mean_pointer,
    inv_std_pointer,
    output_pointer,
    running_mean_pointer,
    running_var_pointer,
    batch_dim,
    spatial_dim,
    input_batch_stride,
    input_feat_stride,
    input_spatial_stride,
    output_batch_stride,
    output_feat_stride,
    output_spatial_stride,
    weight_stride,
    bias_stride,
    running_mean_stride,
    running_var_stride,
    momentum,
    eps,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
    IS_FP64: tl.constexpr = False,
):
    feat_pid = tl.program_id(axis=0)

    # Training mode: compute batch statistics and update running stats.
    # Accumulate in FP64 for FP64 inputs, FP32 otherwise.
    ACC_DTYPE = tl.float64 if IS_FP64 else tl.float32
    mean = tl.zeros((BLOCK_M, BLOCK_N), dtype=ACC_DTYPE)
    var = tl.zeros((BLOCK_M, BLOCK_N), dtype=ACC_DTYPE)
    cnt = tl.zeros((BLOCK_M, BLOCK_N), dtype=tl.int32)

    m_num_steps = tl.cdiv(batch_dim, BLOCK_M)
    n_num_steps = tl.cdiv(spatial_dim, BLOCK_N)

    for m_step in range(0, m_num_steps):
        for n_step in range(0, n_num_steps):
            spatial_offset = n_step * BLOCK_N + tl.arange(0, BLOCK_N)
            spatial_mask = spatial_offset < spatial_dim

            batch_offset = m_step * BLOCK_M + tl.arange(0, BLOCK_M)
            batch_mask = batch_offset < batch_dim

            curr_input_pointer = (
                input_pointer
                + input_feat_stride * feat_pid
                + input_batch_stride * batch_offset[:, None]
                + input_spatial_stride * spatial_offset[None, :]
            )

            mask = batch_mask[:, None] & spatial_mask[None, :]
            curr_input = tl.load(curr_input_pointer, mask=mask).to(ACC_DTYPE)

            # Use the per-lane valid count as the denominator. A global tile
            # index would over-count lanes that are masked out in earlier
            # tiles (e.g. a masked spatial tail followed by more batch tiles).
            new_mean = tl.where(mask, mean + (curr_input - mean) / (cnt + 1), mean)
            new_var = tl.where(
                mask, var + (curr_input - new_mean) * (curr_input - mean), var
            )
            cnt += mask.to(tl.int32)
            mean = new_mean
            var = new_var

    final_mean = tl.sum(mean * cnt) / (batch_dim * spatial_dim)
    var = tl.sum(var + cnt * (mean - final_mean) * (mean - final_mean)) / (
        batch_dim * spatial_dim
    )
    if IS_FP64:
        inv_std = 1.0 / tl.sqrt(var + eps)
    else:
        inv_std = tl.math.rsqrt(var + eps)
    mean = final_mean

    tl.store(feat_pid + mean_pointer, mean)
    tl.store(feat_pid + inv_std_pointer, inv_std)

    running_mean_pointer += feat_pid * running_mean_stride
    running_var_pointer += feat_pid * running_var_stride

    running_mean = tl.load(running_mean_pointer)
    running_var = tl.load(running_var_pointer)

    n = batch_dim * spatial_dim
    tl.store(running_mean_pointer, (1 - momentum) * running_mean + momentum * mean)
    tl.store(
        running_var_pointer,
        (1 - momentum) * running_var + momentum * var * n / (n - 1),
    )

    if weight_pointer:
        weight = tl.load(feat_pid * weight_stride + weight_pointer).to(ACC_DTYPE)
    else:
        weight = tl.full((), 1.0, dtype=ACC_DTYPE)
    if bias_pointer:
        bias = tl.load(feat_pid * bias_stride + bias_pointer).to(ACC_DTYPE)
    else:
        bias = tl.full((), 0.0, dtype=ACC_DTYPE)

    for m_step in range(0, tl.cdiv(batch_dim, BLOCK_M)):
        for n_step in range(0, tl.cdiv(spatial_dim, BLOCK_N)):
            batch_offset = m_step * BLOCK_M + tl.arange(0, BLOCK_M)
            batch_mask = batch_offset < batch_dim

            spatial_offset = n_step * BLOCK_N + tl.arange(0, BLOCK_N)
            spatial_mask = spatial_offset < spatial_dim

            curr_input_pointer = (
                input_pointer
                + input_feat_stride * feat_pid
                + input_batch_stride * batch_offset[:, None]
                + input_spatial_stride * spatial_offset[None, :]
            )
            curr_output_pointer = (
                output_pointer
                + output_feat_stride * feat_pid
                + output_batch_stride * batch_offset[:, None]
                + output_spatial_stride * spatial_offset[None, :]
            )

            curr_input = tl.load(
                curr_input_pointer, mask=batch_mask[:, None] & spatial_mask[None, :]
            ).to(ACC_DTYPE)
            output = weight * (curr_input - mean) * inv_std + bias

            tl.store(
                curr_output_pointer,
                output.to(output_pointer.dtype.element_ty),
                mask=batch_mask[:, None] & spatial_mask[None, :],
            )


def _batch_norm_with_update(
    input: Tensor,
    weight=None,
    bias=None,
    running_mean=None,
    running_var=None,
    momentum=0.1,
    eps=1e-05,
):
    """Training-mode batch normalization that updates running stats in place.

    Matches aten::_batch_norm_with_update, returning
    (output, save_mean, save_invstd, reserve). running_mean and running_var
    are updated in place.
    """
    logger.debug("GEMS _BATCH_NORM_WITH_UPDATE")

    input_3d = make_3d_for_bn(input)

    batch_dim, feat_dim, spatial_dim = input_3d.shape
    output = torch.empty_like(input_3d)

    if running_mean is None or running_var is None:
        raise RuntimeError(
            "_batch_norm_with_update expects running_mean and running_var to be specified."
        )

    # ATen returns accumulation-dtype statistics: FP64 for FP64 inputs,
    # FP32 otherwise.
    is_fp64 = input.dtype == torch.float64
    acc_dtype = torch.float64 if is_fp64 else torch.float32
    mean = torch.empty(feat_dim, device=input.device, dtype=acc_dtype)
    inv_std = torch.empty(feat_dim, device=input.device, dtype=acc_dtype)

    # reserve is an empty uint8 tensor used by cuDNN paths; unused here.
    reserve = torch.empty((0,), dtype=torch.uint8, device=input.device)

    # The kernel indexes these 1-D tensors by feature id, so a length other
    # than feat_dim would read or write outside their storage.
    for name, param in (
        ("weight", weight),
        ("bias", bias),
        ("running_mean", running_mean),
        ("running_var", running_var),
    ):
        if param is not None and param.numel() != feat_dim:
            raise RuntimeError(
                f"_batch_norm_with_update expects {name} to have {feat_dim} elements, "
                f"but got {param.numel()}."
            )

    # Empty batch or spatial dimensions carry no elements to normalize; the
    # statistics are zeroed instead of returning uninitialized memory.
    if batch_dim == 0 or spatial_dim == 0:
        mean.zero_()
        inv_std.zero_()
        return output.view_as(input), mean, inv_std, reserve

    # Launches 1D grid where each program operates over one feature.
    with torch_device_fn.device(input.device):
        batch_norm_with_update_kernel[(feat_dim,)](
            input_3d,
            weight,
            bias,
            mean,
            inv_std,
            output,
            running_mean,
            running_var,
            batch_dim,
            spatial_dim,
            *input_3d.stride(),
            *output.stride(),
            weight.stride(0) if weight is not None else 1,
            bias.stride(0) if bias is not None else 1,
            running_mean.stride(0),
            running_var.stride(0),
            momentum,
            eps,
            IS_FP64=is_fp64,
        )

    # save_invstd is 1/sqrt(var + eps), matching PyTorch's convention.
    save_invstd = inv_std

    return output.view_as(input), mean, save_invstd, reserve
