# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn

logger = logging.getLogger(__name__)


@triton.jit
def _pack_4bit_weight_kernel(
    weights,
    scales_zeros,
    bias,
    output,
    weight_elements,
    scale_elements,
    total_elements,
    HAS_BIAS: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    offsets = tl.program_id(0).to(tl.int64) * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < total_elements
    values = tl.zeros((BLOCK_SIZE,), dtype=tl.float32)

    weight_mask = mask & (offsets < weight_elements)
    values = tl.where(
        weight_mask,
        tl.load(weights + offsets, mask=weight_mask, other=0).to(tl.float32),
        values,
    )

    scale_offsets = offsets - weight_elements
    scale_mask = mask & (scale_offsets >= 0) & (scale_offsets < scale_elements)
    values = tl.where(
        scale_mask,
        tl.load(scales_zeros + scale_offsets, mask=scale_mask, other=0.0).to(
            tl.float32
        ),
        values,
    )

    if HAS_BIAS:
        bias_offsets = scale_offsets - scale_elements
        bias_mask = mask & (bias_offsets >= 0)
        values = tl.where(
            bias_mask,
            tl.load(bias + bias_offsets, mask=bias_mask, other=0.0).to(tl.float32),
            values,
        )

    tl.store(output + offsets, values, mask=mask)


def _dyn_quant_pack_4bit_weight(
    weights: torch.Tensor,
    scales_zeros: torch.Tensor,
    bias: torch.Tensor | None,
    block_size: int,
    in_features: int,
    out_features: int,
) -> torch.Tensor:
    """Pack INT4 weights into the portable ABI consumed by the generic matmul.

    For K=in_features, N=out_features and G=K/block_size, weights is uint8
    [N, K/2]. Each byte stores the even-K value in its low nibble and the
    odd-K value in its high nibble; a nibble represents signed INT4 as value-8.
    scales_zeros contains scales only, as [N, G] or a flat [N*G] tensor in
    output-channel-major order. Optional bias has shape [N]. Scales and bias
    may be float16, bfloat16 or float32, on the weights device.

    The result is a contiguous 1D float32 tensor on that same device:
    [weights.flatten().float(), scales_zeros.flatten().float(), optional bias].
    Segment lengths are N*K/2, N*G and either zero or N, respectively. This
    format is distinct from the opaque uint8 CPU KleidiAI packing. K must be
    positive and even; N may be zero, in which case no kernel is launched.
    """
    logger.debug("GEMS _DYN_QUANT_PACK_4BIT_WEIGHT")
    if in_features <= 0 or in_features % 2 != 0:
        raise RuntimeError("in_features must be positive and even for INT4 packing")
    if out_features < 0:
        raise RuntimeError("out_features must be nonnegative")
    if block_size <= 0:
        raise RuntimeError("block_size must be positive")
    if weights.dtype != torch.uint8:
        raise RuntimeError("_dyn_quant_pack_4bit_weight expects uint8 weights")
    if weights.ndim != 2 or weights.shape != (out_features, in_features // 2):
        raise RuntimeError("weights must have shape [out_features, in_features / 2]")
    if block_size != in_features and (
        block_size % 32 != 0 or in_features % block_size != 0
    ):
        raise RuntimeError(
            "group size must equal in_features or divide it as a multiple of 32"
        )
    groups = in_features // block_size
    scale_elements = out_features * groups
    if not (
        (scales_zeros.ndim == 1 and scales_zeros.numel() == scale_elements)
        or (scales_zeros.ndim == 2 and scales_zeros.shape == (out_features, groups))
    ):
        raise RuntimeError(
            "scales_zeros must have shape [out_features, in_features / block_size] "
            "or its flat equivalent"
        )
    parameter_dtypes = (torch.float16, torch.bfloat16, torch.float32)
    if scales_zeros.dtype not in parameter_dtypes:
        raise RuntimeError("scales_zeros must have dtype float16, bfloat16 or float32")
    if bias is not None:
        if bias.ndim != 1 or bias.numel() != out_features:
            raise RuntimeError("bias must have shape [out_features]")
        if bias.dtype not in parameter_dtypes:
            raise RuntimeError("bias must have dtype float16, bfloat16 or float32")
    if scales_zeros.device != weights.device or (
        bias is not None and bias.device != weights.device
    ):
        raise RuntimeError("weights, scales_zeros, and bias must be on the same device")

    weights = weights.contiguous()
    scales_zeros = scales_zeros.contiguous()
    if bias is not None:
        bias = bias.contiguous()

    weight_elements = out_features * (in_features // 2)
    bias_elements = 0 if bias is None else out_features
    total_elements = weight_elements + scale_elements + bias_elements
    output = torch.empty(total_elements, device=weights.device, dtype=torch.float32)
    if total_elements == 0:
        return output

    bias_arg = weights if bias is None else bias
    # A 256-element tile balances launch overhead and coalesced sequential copies.
    grid = (triton.cdiv(total_elements, 256),)
    with torch_device_fn.device(weights.device):
        _pack_4bit_weight_kernel[grid](
            weights,
            scales_zeros,
            bias_arg,
            output,
            weight_elements,
            scale_elements,
            total_elements,
            HAS_BIAS=bias is not None,
            # Match the launch tile used to build the grid.
            BLOCK_SIZE=256,
        )
    return output
