# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen

import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _nested_tensor_softmax_with_shape_kernel(
    input_ptr,
    output_ptr,
    seq_lens_ptr,
    n_cols,
    n_heads,
    BLOCK_SIZE: tl.constexpr,
):
    """Kernel for the nested-tensor softmax-with-shape operation.

    The input is a padded attention matrix of shape ``[B, T_max, H, T_max]``
    (``B`` batches, ``H`` heads, and a ``T_max x T_max`` per-head attention
    block).  For every batch ``b`` the sequence length ``T_b`` is read from
    ``seq_lens``, and each ``(s, h)`` row is softmax'ed over the first ``T_b``
    columns.  Rows with ``s >= T_b`` and columns with ``t >= T_b`` are set to 0.
    """

    # Flattened row layout over the padded tensor: row = (b * T_max + s) * H + h.
    row = tl.program_id(0)
    b = row // (n_cols * n_heads)
    rem = row % (n_cols * n_heads)
    s = rem // n_heads

    seq_len = tl.load(seq_lens_ptr + b)

    cols = tl.arange(0, BLOCK_SIZE)
    mask = cols < n_cols
    base = row * n_cols

    x = tl.load(input_ptr + base + cols, mask=mask, other=-float("inf")).to(tl.float32)

    col_valid = cols < seq_len
    x_masked = tl.where(col_valid, x, -float("inf"))

    x_max = tl.max(x_masked, axis=0)
    exp_x = tl.exp(x_masked - x_max)
    sum_exp = tl.sum(exp_x, axis=0)
    softmax = exp_x / sum_exp

    row_valid = s < seq_len
    softmax = tl.where(col_valid, softmax, 0.0)
    softmax = tl.where(row_valid, softmax, 0.0)

    tl.store(output_ptr + base + cols, softmax, mask=mask)


def _next_pow2(v: int) -> int:
    if v <= 1:
        return 1
    return 1 << (v - 1).bit_length()


def _nested_tensor_softmax_with_shape(
    self: torch.Tensor, query: torch.Tensor
) -> torch.Tensor:
    """Nested-tensor softmax that derives the softmax shape from ``query``.

    ``self`` is a nested tensor of per-head attention scores and ``query`` is a
    nested tensor whose ragged dimension encodes the per-batch sequence length.
    The per-batch softmax is computed over the last (column) dimension and the
    out-of-range entries are masked to zero, matching
    ``torch.ops.aten._nested_tensor_softmax_with_shape``.
    """
    logger.debug("GEMS _NESTED_TENSOR_SOFTMAX_WITH_SHAPE")

    # attn: [B, T_max, H, T_max]
    attn = self.to_padded_tensor(0.0).contiguous()
    B, T_max, H, _ = attn.shape

    offsets = query.offsets()
    seq_lens = (offsets[1:] - offsets[:-1]).to(torch.int32).contiguous()

    out = torch.empty_like(attn)
    n_rows = B * T_max * H
    BLOCK_SIZE = min(4096, _next_pow2(T_max))
    grid = (n_rows,)
    _nested_tensor_softmax_with_shape_kernel[grid](
        attn, out, seq_lens, T_max, H, BLOCK_SIZE=BLOCK_SIZE
    )
    return out
