# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _pad_packed_sequence_kernel(
    data,
    batch_sizes,
    time_offsets,
    output,
    padding_value,
    num_steps: tl.constexpr,
    max_batch: tl.constexpr,
    feature_size: tl.constexpr,
    out_stride_t,
    out_stride_b,
    BLOCK_SIZE: tl.constexpr,
):
    """Scatter a packed sequence back into a padded (T, B, *) tensor.

    Each program handles one (t, b) output row: it either copies the
    corresponding packed feature vector or fills the row with padding_value.

    Args:
        data: 2D packed tensor of shape (sum(batch_sizes), feature_size)
        batch_sizes: 1D int64 tensor, number of active batch elements per step
        time_offsets: 1D int64 tensor, exclusive prefix sum of batch_sizes
        output: flattened padded output buffer
        padding_value: scalar fill value for padded positions
        num_steps: number of valid time steps (batch_sizes.numel())
        max_batch: batch size (batch_sizes[0])
        feature_size: trailing feature dimension of data
        out_stride_t, out_stride_b: output row strides for time / batch axes
        BLOCK_SIZE: feature tile size
    """
    pid = tle.program_id(axis=0)
    t = pid // max_batch
    b = pid % max_batch

    row_offset = t * out_stride_t + b * out_stride_b

    # Positions past the packed sequence length for this batch element are
    # padded; t >= num_steps is always padding.
    step_active = t < num_steps
    bs_t = tl.load(batch_sizes + t, mask=step_active, other=0)

    if b < bs_t:
        src_row = tl.load(time_offsets + t) + b
        src_offset = src_row * feature_size
        for j in tl.range(0, feature_size, BLOCK_SIZE):
            cols = j + tl.arange(0, BLOCK_SIZE)
            mask = cols < feature_size
            vals = tl.load(data + src_offset + cols, mask=mask)
            tl.store(output + row_offset + cols, vals, mask=mask)
    else:
        for j in tl.range(0, feature_size, BLOCK_SIZE):
            cols = j + tl.arange(0, BLOCK_SIZE)
            mask = cols < feature_size
            tl.store(output + row_offset + cols, padding_value, mask=mask)


def _pad_packed_sequence(data, batch_sizes, batch_first, padding_value, total_length):
    """Pad a packed variable-length sequence back into a dense tensor.

    Inverse of ``_pack_padded_sequence``: scatters ``data`` (shape
    ``(sum(batch_sizes), *)``) into a padded ``(T, B, *)`` tensor (or
    ``(B, T, *)`` when ``batch_first``) and returns it together with the
    per-batch-element sequence lengths.

    Args:
        data: packed values tensor.
        batch_sizes: 1D CPU int64 tensor of active counts per time step.
        batch_first: if True, output layout is (B, T, *) instead of (T, B, *).
        padding_value: value used for padded positions.
        total_length: pad the time dimension out to at least this many steps;
            values <= 0 mean use the number of steps in ``batch_sizes``.

    Returns:
        Tuple of (padded output tensor, lengths tensor).
    """
    logger.debug("GEMS _PAD_PACKED_SEQUENCE")

    num_steps = batch_sizes.numel()
    max_batch = int(batch_sizes[0].item())

    total_steps = num_steps
    if total_length > 0:
        total_steps = max(total_steps, int(total_length))

    # batch_sizes is a CPU int64 tensor (aten contract). Derive the exclusive
    # prefix sum (packed offset of each time step) and per-element lengths on
    # host, then move the small metadata tensors to the compute device. The
    # metadata arithmetic stays on CPU so it is never dispatched through the
    # gems pointwise kernels (the tensors are tiny and host-resident already).
    # Both device tensors are shipped in one concatenated H2D copy to keep the
    # small-shape launch path at a single transfer.
    batch_sizes_cpu = batch_sizes.to(dtype=torch.int64, device="cpu")
    time_offsets_cpu = torch.zeros_like(batch_sizes_cpu)
    time_offsets_cpu[1:] = torch.cumsum(batch_sizes_cpu[:-1], dim=0)
    lengths = torch.searchsorted(
        torch.flip(batch_sizes_cpu, [0]),
        torch.arange(max_batch, dtype=torch.int64),
        right=True,
    )
    lengths = (num_steps - lengths).to(torch.int64)

    metadata_dev = torch.cat([batch_sizes_cpu, time_offsets_cpu]).to(data.device)
    batch_sizes_dev = metadata_dev[:num_steps]
    time_offsets = metadata_dev[num_steps:]

    feature_shape = data.shape[1:]
    feature_size = 1
    for s in feature_shape:
        feature_size *= s

    output = torch.empty(
        (total_steps, max_batch, *feature_shape),
        dtype=data.dtype,
        device=data.device,
    )
    out_flat = output.view(total_steps, max_batch, feature_size)

    out_stride_t = out_flat.stride(0)
    out_stride_b = out_flat.stride(1)

    grid = (total_steps * max_batch,)
    # BLOCK_SIZE=1024 balances occupancy and register use for typical feature
    # widths; larger features are handled by the in-kernel range loop.
    BLOCK_SIZE = min(1024, max(1, triton.next_power_of_2(feature_size)))

    _pad_packed_sequence_kernel[grid](
        data.reshape(-1),
        batch_sizes_dev,
        time_offsets,
        out_flat,
        padding_value,
        num_steps,
        max_batch,
        feature_size,
        out_stride_t,
        out_stride_b,
        BLOCK_SIZE=BLOCK_SIZE,
    )

    if batch_first:
        output = output.transpose(0, 1).contiguous()

    return output, lengths.cpu()
