# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry
from flag_gems.utils.random_utils import (
    philox_backend_seed_offset,
    uint_to_uniform_float,
)

logger = logging.getLogger(__name__)


@triton.jit
def sample_gamma_marsaglia_tsang(
    alpha, seed, c0, c1, z, MAX_ITER: tl.constexpr, COMPUTE_DTYPE: tl.constexpr
):
    """
    Sample from Gamma(alpha, 1) using Marsaglia-Tsang method.
    For alpha < 1, use the transformation:
        Gamma(alpha) = Gamma(alpha+1) * U^(1/alpha)

    All arithmetic runs in COMPUTE_DTYPE so an fp64 input keeps double
    precision through the rejection loop and the tail correction.
    """
    alpha = alpha.to(COMPUTE_DTYPE)

    # For alpha < 1, boost to alpha + 1
    alpha_orig = alpha
    alpha_boosted = tl.where(alpha < 1.0, alpha + 1.0, alpha)

    d = alpha_boosted - 1.0 / 3.0
    c = 1.0 / tl.sqrt(9.0 * d)

    # Rejection sampling loop. Marsaglia-Tsang has a very high acceptance
    # rate (> 95% per iteration), so nearly every lane accepts within a
    # few draws. `result` is locked to the *first* acceptance (guarded by
    # `~done`), so once every lane in the block has accepted there is
    # nothing left to compute and we exit early. For a given seed this
    # yields the exact same value as running the full loop; MAX_ITER only
    # bounds the worst case. Each iteration draws philox at counter
    # c0 + iter*4, so iterations never share randomness.
    result = alpha * 0.0
    done = alpha < 0.0  # Initialize to all False

    iter = 0
    n_remaining = tl.sum((~done).to(tl.int32))
    while (iter < MAX_ITER) and (n_remaining > 0):
        # Generate normal sample using Box-Muller
        r0, r1, r2, r3 = tl.philox(seed, c0 + iter * 4, c1, z, z)
        u1 = tl.maximum(uint_to_uniform_float(r0).to(COMPUTE_DTYPE), 1e-10)
        u2 = uint_to_uniform_float(r1).to(COMPUTE_DTYPE)
        v_uniform = uint_to_uniform_float(r2).to(COMPUTE_DTYPE)

        radius = tl.sqrt(-2.0 * tl.log(u1))
        theta = 6.283185307179586 * u2
        x = radius * tl.cos(theta)

        v = 1.0 + c * x

        # Check if v > 0
        valid_v = v > 0.0

        v3 = v * v * v
        log_v = tl.log(v)

        # Acceptance condition: U < 1 - 0.0331*x^4 (squeeze)
        # or log(U) < 0.5*x^2 + d*(1 - v^3 + log(v^3))
        x2 = x * x
        squeeze = 1.0 - 0.0331 * x2 * x2
        accept_squeeze = v_uniform < squeeze

        log_condition = tl.log(v_uniform) < (0.5 * x2 + d * (1.0 - v3 + 3.0 * log_v))
        accept = valid_v & (accept_squeeze | log_condition)

        # Update result for accepted samples (only if not already done)
        gamma_sample = d * v3
        result = tl.where(~done & accept, gamma_sample, result)
        done = done | accept

        iter += 1
        n_remaining = tl.sum((~done).to(tl.int32))

    # For alpha < 1, apply correction: multiply by U^(1/alpha). The correction
    # draws at a fixed counter past the loop's range (MAX_ITER*4 + 4), so it is
    # independent of how many rejection iterations each lane actually consumed.
    r0, r1, r2, r3 = tl.philox(seed, c0 + MAX_ITER * 4 + 4, c1, z, z)
    u_correct = tl.maximum(uint_to_uniform_float(r0).to(COMPUTE_DTYPE), 1e-10)
    correction = tl.exp(tl.log(u_correct) / alpha_orig)
    result = tl.where(alpha_orig < 1.0, result * correction, result)

    return result


@libentry()
@triton.jit(do_not_specialize=["philox_seed", "philox_offset", "N", "K"])
def sample_dirichlet_kernel(
    alpha_ptr,
    out_ptr,
    N,
    K,
    philox_seed,
    philox_offset,
    tiny_ptr,
    BLOCK_K: tl.constexpr,
    MAX_ITER: tl.constexpr,
    COMPUTE_DTYPE: tl.constexpr,
):
    """
    Sample from Dirichlet distribution.
    Input shape: [N, K], output shape: [N, K]
    Each row is normalized to sum to 1.

    A Dirichlet draw is Gamma(alpha_k) / sum_j Gamma(alpha_j), so the row must
    be normalized by the *full* row sum. When K spans more than one BLOCK_K the
    per-element gammas cannot be normalized until every block has contributed to
    the sum, so this kernel makes two passes over the row:

      1. sample each gamma and accumulate the full-row sum;
      2. re-sample each gamma (deterministic under the same philox counter) and
         divide by the full-row sum.

    Re-sampling avoids stashing the raw gammas in the low-precision output
    buffer, so the normalization stays in COMPUTE_DTYPE.
    """
    philox_seed = philox_seed.to(tl.int64)
    philox_offset = philox_offset.to(tl.int64)

    row_id = tl.program_id(0)

    if row_id >= N:
        return

    # Load the clamp floor in COMPUTE_DTYPE. It must come through a pointer of
    # the input dtype: a Python-float kernel arg is coerced to fp32 and fp64's
    # tiny (2.2e-308) would underflow to zero, defeating the clamp.
    tiny = tl.load(tiny_ptr).to(COMPUTE_DTYPE)

    # Pass 1: accumulate the full-row gamma sum in COMPUTE_DTYPE.
    gamma_sum = tl.zeros([], dtype=COMPUTE_DTYPE)
    for k_start in range(0, K, BLOCK_K):
        k_offs = k_start + tl.arange(0, BLOCK_K)
        mask = k_offs < K

        alpha_idx = row_id * K + k_offs
        alpha = tl.load(alpha_ptr + alpha_idx, mask=mask, other=1.0)

        counter_base = philox_offset + alpha_idx.to(tl.int64) * 512
        c0 = (counter_base & 0xFFFFFFFF).to(tl.uint32)
        c1 = ((counter_base >> 32) & 0xFFFFFFFF).to(tl.uint32)
        z = c0 * 0

        gamma = sample_gamma_marsaglia_tsang(
            alpha, philox_seed, c0, c1, z, MAX_ITER, COMPUTE_DTYPE
        )
        # ATen clamps each gamma draw to the output dtype's smallest positive
        # value so tiny-alpha rows (whose boost factor U**(1/alpha) underflows
        # to zero) still sum to a well-defined 1 instead of 0/0.
        gamma = tl.maximum(gamma, tiny)
        gamma_sum += tl.sum(tl.where(mask, gamma, 0.0).to(COMPUTE_DTYPE))

    # Every gamma was clamped to tiny, so gamma_sum >= K * tiny > 0; no epsilon
    # floor is needed (and a fixed floor like 1e-30 would corrupt fp32 rows whose
    # true sum, ~K * 1.18e-38, legitimately falls below it).
    inv_sum = 1.0 / gamma_sum

    # Pass 2: re-sample each gamma with the identical counters and normalize.
    for k_start in range(0, K, BLOCK_K):
        k_offs = k_start + tl.arange(0, BLOCK_K)
        mask = k_offs < K

        alpha_idx = row_id * K + k_offs
        alpha = tl.load(alpha_ptr + alpha_idx, mask=mask, other=1.0)

        counter_base = philox_offset + alpha_idx.to(tl.int64) * 512
        c0 = (counter_base & 0xFFFFFFFF).to(tl.uint32)
        c1 = ((counter_base >> 32) & 0xFFFFFFFF).to(tl.uint32)
        z = c0 * 0

        gamma = sample_gamma_marsaglia_tsang(
            alpha, philox_seed, c0, c1, z, MAX_ITER, COMPUTE_DTYPE
        )
        gamma = tl.maximum(gamma, tiny)
        normalized = gamma * inv_sum
        tl.store(
            out_ptr + alpha_idx, normalized.to(out_ptr.dtype.element_ty), mask=mask
        )


def _sample_dirichlet(input, generator=None):
    """
    Sample from Dirichlet distribution.

    Args:
        input: Tensor of shape [..., K] containing alpha parameters
        generator: Optional random generator

    Returns:
        Tensor of same shape as input, where each K-dimensional vector
        sums to 1
    """
    logger.debug("GEMS _SAMPLE_DIRICHLET")

    assert input.dtype in (
        torch.float16,
        torch.bfloat16,
        torch.float32,
        torch.float64,
    ), f"Unsupported dtype: {input.dtype}"

    # Flatten all but last dimension
    orig_shape = input.shape
    if input.ndim == 0:
        # Scalar input - unsqueeze to [1]
        input = input.unsqueeze(0)

    if input.ndim == 1:
        K = input.shape[0]
        N = 1
        inp = input.unsqueeze(0)
    else:
        inp = input.reshape(-1, input.shape[-1])
        N = inp.shape[0]
        K = inp.shape[1]

    inp = inp.contiguous()
    out = torch.empty_like(inp)

    if N == 0 or K == 0:
        return out.reshape(orig_shape)

    # Calculate philox increment
    increment = triton.cdiv(N * K * 512, 4)
    philox_seed, philox_offset = philox_backend_seed_offset(
        increment, generator=generator
    )

    # Use power-of-2 block size
    BLOCK_K = triton.next_power_of_2(min(K, 1024))

    # Worst-case rejection iterations. Marsaglia-Tsang accepts in ~1 draw on
    # average; the kernel exits as soon as every lane has accepted, so this is
    # only a safety bound and is rarely reached.
    MAX_ITER = 100

    # fp64 inputs keep double precision through sampling and normalization;
    # every other float dtype samples in fp32 (its uniforms have only fp32
    # granularity anyway) and rounds to the output dtype on store.
    compute_dtype = tl.float64 if inp.dtype == torch.float64 else tl.float32

    # Smallest positive value of the input dtype; each gamma draw is clamped to
    # it so tiny-alpha rows never collapse to an all-zero (0/0) normalization.
    # Passed as a 0-d tensor (not a Python float) to keep fp64 precision.
    tiny = torch.tensor(torch.finfo(inp.dtype).tiny, dtype=inp.dtype, device=inp.device)

    grid = (N,)
    with torch_device_fn.device(inp.device):
        sample_dirichlet_kernel[grid](
            inp,
            out,
            N,
            K,
            philox_seed,
            philox_offset,
            tiny,
            BLOCK_K=BLOCK_K,
            MAX_ITER=MAX_ITER,
            COMPUTE_DTYPE=compute_dtype,
        )

    return out.reshape(orig_shape)
