# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

logger = logging.getLogger(__name__)


@triton.jit
def _fused_attn_kernel(
    Q,
    K,
    V,
    Out,
    AW,
    scale,
    Sq,
    Sk,
    D,
    Dv,
    stride_qb,
    stride_qm,
    stride_qd,
    stride_kb,
    stride_kn,
    stride_kd,
    stride_vb,
    stride_vn,
    stride_vd,
    stride_ob,
    stride_om,
    stride_od,
    stride_wb,
    stride_wm,
    stride_wn,
    IS_CAUSAL: tl.constexpr,
    BM: tl.constexpr,
    BN: tl.constexpr,
    BD: tl.constexpr,
    BDV: tl.constexpr,
):
    pid_b = tl.program_id(0)
    pid_m = tl.program_id(1)

    offs_m = pid_m * BM + tl.arange(0, BM)
    offs_d = tl.arange(0, BD)
    offs_dv = tl.arange(0, BDV)

    q_ptrs = (
        Q
        + pid_b * stride_qb
        + offs_m[:, None] * stride_qm
        + offs_d[None, :] * stride_qd
    )
    q = tl.load(q_ptrs, mask=(offs_m[:, None] < Sq) & (offs_d[None, :] < D), other=0.0)

    m_i = tl.full([BM], -float("inf"), tl.float32)
    l_i = tl.zeros([BM], tl.float32)
    diag = Sk - Sq

    if IS_CAUSAL:
        hi = pid_m * BM + BM + diag
        if hi > Sk:
            hi = Sk
    else:
        hi = Sk

    # Pass 1: online softmax statistics
    for n0 in range(0, hi, BN):
        offs_n = n0 + tl.arange(0, BN)
        k_ptrs = (
            K
            + pid_b * stride_kb
            + offs_n[:, None] * stride_kn
            + offs_d[None, :] * stride_kd
        )
        k = tl.load(
            k_ptrs, mask=(offs_n[:, None] < Sk) & (offs_d[None, :] < D), other=0.0
        )
        s = tl.dot(q, tl.trans(k)).to(tl.float32) * scale
        valid = offs_n[None, :] < Sk
        if IS_CAUSAL:
            valid = valid & (offs_n[None, :] <= offs_m[:, None] + diag)
        s = tl.where(valid, s, -float("inf"))
        m_new = tl.maximum(m_i, tl.max(s, axis=1))
        alpha = tl.exp(m_i - m_new)
        p = tl.exp(s - m_new[:, None])
        l_i = l_i * alpha + tl.sum(p, axis=1)
        m_i = m_new

    l_safe = tl.where(l_i == 0.0, 1.0, l_i)
    inv_l = 1.0 / l_safe

    # Pass 2: write normalized weights and accumulate output
    acc = tl.zeros([BM, BDV], tl.float32)
    for n0 in range(0, hi, BN):
        offs_n = n0 + tl.arange(0, BN)
        k_ptrs = (
            K
            + pid_b * stride_kb
            + offs_n[:, None] * stride_kn
            + offs_d[None, :] * stride_kd
        )
        k = tl.load(
            k_ptrs, mask=(offs_n[:, None] < Sk) & (offs_d[None, :] < D), other=0.0
        )
        s = tl.dot(q, tl.trans(k)).to(tl.float32) * scale
        valid = offs_n[None, :] < Sk
        if IS_CAUSAL:
            valid = valid & (offs_n[None, :] <= offs_m[:, None] + diag)
        s = tl.where(valid, s, -float("inf"))
        p = tl.exp(s - m_i[:, None]) * inv_l[:, None]

        w_ptrs = (
            AW
            + pid_b * stride_wb
            + offs_m[:, None] * stride_wm
            + offs_n[None, :] * stride_wn
        )
        w_mask = (offs_m[:, None] < Sq) & (offs_n[None, :] < Sk)
        tl.store(w_ptrs, p.to(AW.dtype.element_ty), mask=w_mask)

        v_ptrs = (
            V
            + pid_b * stride_vb
            + offs_n[:, None] * stride_vn
            + offs_dv[None, :] * stride_vd
        )
        v = tl.load(
            v_ptrs, mask=(offs_n[:, None] < Sk) & (offs_dv[None, :] < Dv), other=0.0
        )
        acc += tl.dot(p.to(v.dtype), v)

    # Zero-fill fully-masked (causal) K blocks that pass 2 skipped.
    if IS_CAUSAL:
        zero_row = tl.zeros([BM, BN], AW.dtype.element_ty)
        for n0 in range(hi, Sk, BN):
            offs_n = n0 + tl.arange(0, BN)
            w_ptrs = (
                AW
                + pid_b * stride_wb
                + offs_m[:, None] * stride_wm
                + offs_n[None, :] * stride_wn
            )
            w_mask = (offs_m[:, None] < Sq) & (offs_n[None, :] < Sk)
            tl.store(w_ptrs, zero_row, mask=w_mask)

    o_ptrs = (
        Out
        + pid_b * stride_ob
        + offs_m[:, None] * stride_om
        + offs_dv[None, :] * stride_od
    )
    tl.store(
        o_ptrs,
        acc.to(Out.dtype.element_ty),
        mask=(offs_m[:, None] < Sq) & (offs_dv[None, :] < Dv),
    )


def _scaled_dot_product_attention_math_for_mps(
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attn_mask: torch.Tensor = None,
    dropout_p: float = 0.0,
    is_causal: bool = False,
    dropout_mask: torch.Tensor = None,
    *,
    scale: float = None,
):
    """FlagGems implementation of aten::_scaled_dot_product_attention_math_for_mps.

    Math reference of scaled dot-product attention that returns BOTH the
    attention output and the full softmax attention-weight matrix.

    Args:
        query: (batch, num_heads, seq_len_q, head_dim)
        key: (batch, num_heads, seq_len_kv, head_dim)
        value: (batch, num_heads, seq_len_kv, head_dim_v)
        attn_mask: Optional additive attention mask (unsupported, must be None)
        dropout_p: Dropout probability (only 0.0 is supported)
        is_causal: Whether to apply a causal mask
        dropout_mask: Optional precomputed dropout mask (unsupported, must be None)
        scale: Optional scale factor for the QK dot product

    Returns:
        Tuple of (output, attn_weights) where attn_weights is the full
        softmax attention-weight matrix of shape (batch, num_heads, seq_len_q,
        seq_len_kv).
    """
    logger.debug("GEMS _SCALED_DOT_PRODUCT_ATTENTION_MATH_FOR_MPS")

    assert dropout_p == 0.0, "Only dropout_p=0.0 is supported"
    assert attn_mask is None, "attn_mask is not supported"
    assert dropout_mask is None, "dropout_mask is not supported"
    assert query.shape[-1] == key.shape[-1], "query/key head_dim must match"

    q = query.contiguous()
    k = key.contiguous()
    v = value.contiguous()

    B, H, Sq, D = q.shape
    Sk = k.shape[-2]
    Dv = v.shape[-1]
    BH = B * H

    if scale is None:
        scale = 1.0 / (D**0.5)
    else:
        scale = float(scale)

    attn = torch.empty((B, H, Sq, Sk), dtype=q.dtype, device=q.device)
    out = torch.empty((B, H, Sq, Dv), dtype=q.dtype, device=q.device)

    # Inputs are made contiguous above, so per-(batch*head) strides are dense.
    q_sb, q_sm, q_sd = Sq * D, D, 1
    k_sb, k_sn, k_sd = Sk * D, D, 1
    v_sb, v_sn, v_sd = Sk * Dv, Dv, 1
    s_sb, s_sm, s_sn = Sq * Sk, Sk, 1
    o_sb, o_sm, o_sd = Sq * Dv, Dv, 1

    BD = triton.next_power_of_2(D)
    BDV = triton.next_power_of_2(Dv)
    # 64x64 tiles with 4 warps / 2 stages are near-optimal for these attention
    # shapes (small head_dim, few batch*head groups) where SM occupancy is the
    # binding constraint; larger BM/BN regressed timing in tuning.
    BM = 64
    BN = 64

    grid = (BH, triton.cdiv(Sq, BM))
    _fused_attn_kernel[grid](
        q.view(BH, Sq, D),
        k.view(BH, Sk, D),
        v.view(BH, Sk, Dv),
        out.view(BH, Sq, Dv),
        attn.view(BH, Sq, Sk),
        scale,
        Sq,
        Sk,
        D,
        Dv,
        q_sb,
        q_sm,
        q_sd,
        k_sb,
        k_sn,
        k_sd,
        v_sb,
        v_sn,
        v_sd,
        o_sb,
        o_sm,
        o_sd,
        s_sb,
        s_sm,
        s_sn,
        IS_CAUSAL=is_causal,
        BM=BM,
        BN=BN,
        BD=BD,
        BDV=BDV,
        num_warps=4,
        num_stages=2,
    )

    return (out, attn)
