# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.ops.contiguous import contiguous
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _transform_bias_rescale_qkv_kernel(
    qkv_ptr,
    bias_ptr,
    q_ptr,
    k_ptr,
    v_ptr,
    batch,
    seq_len,
    num_heads,
    head_dim,
    scale_factor,
    stride_qkv_b,
    stride_qkv_s,
    stride_qkv_d,
    stride_out_b,
    stride_out_h,
    stride_out_s,
    stride_out_d,
    BLOCK_SIZE: tl.constexpr,
):
    # Each program handles BLOCK_SIZE elements
    pid = tl.program_id(0)

    total_elements = batch * num_heads * seq_len * head_dim

    # Compute indices for this block
    offsets = pid * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < total_elements

    # Decode linear index to [batch, head, seq, head_dim]
    head_dim_idx = offsets % head_dim
    temp = offsets // head_dim
    seq_idx = temp % seq_len
    temp = temp // seq_len
    head_idx = temp % num_heads
    batch_idx = temp // num_heads

    hidden_dim = num_heads * head_dim

    # Calculate input offsets for Q, K, V
    base_offset = batch_idx * stride_qkv_b + seq_idx * stride_qkv_s
    head_offset = head_idx * head_dim + head_dim_idx

    # Load and process Q
    q_input_offset = base_offset + (0 * hidden_dim + head_offset) * stride_qkv_d
    q_bias_offset = 0 * hidden_dim + head_offset
    q_val = tl.load(qkv_ptr + q_input_offset, mask=mask, other=0.0)
    q_bias_val = tl.load(bias_ptr + q_bias_offset, mask=mask, other=0.0)
    q_result = (q_val + q_bias_val) * scale_factor

    # Store Q
    q_output_offset = (
        batch_idx * stride_out_b
        + head_idx * stride_out_h
        + seq_idx * stride_out_s
        + head_dim_idx * stride_out_d
    )
    tl.store(q_ptr + q_output_offset, q_result, mask=mask)

    # Load and process K
    k_input_offset = base_offset + (1 * hidden_dim + head_offset) * stride_qkv_d
    k_bias_offset = 1 * hidden_dim + head_offset
    k_val = tl.load(qkv_ptr + k_input_offset, mask=mask, other=0.0)
    k_bias_val = tl.load(bias_ptr + k_bias_offset, mask=mask, other=0.0)
    k_result = k_val + k_bias_val

    # Store K
    k_output_offset = (
        batch_idx * stride_out_b
        + head_idx * stride_out_h
        + seq_idx * stride_out_s
        + head_dim_idx * stride_out_d
    )
    tl.store(k_ptr + k_output_offset, k_result, mask=mask)

    # Load and process V
    v_input_offset = base_offset + (2 * hidden_dim + head_offset) * stride_qkv_d
    v_bias_offset = 2 * hidden_dim + head_offset
    v_val = tl.load(qkv_ptr + v_input_offset, mask=mask, other=0.0)
    v_bias_val = tl.load(bias_ptr + v_bias_offset, mask=mask, other=0.0)
    v_result = v_val + v_bias_val

    # Store V
    v_output_offset = (
        batch_idx * stride_out_b
        + head_idx * stride_out_h
        + seq_idx * stride_out_s
        + head_dim_idx * stride_out_d
    )
    tl.store(v_ptr + v_output_offset, v_result, mask=mask)


def _transform_bias_rescale_qkv(qkv, qkv_bias, num_heads):
    """Transform QKV tensor with bias addition and query rescaling.

    Args:
        qkv: Input tensor of shape [batch, seq_len, 3 * hidden_dim]
        qkv_bias: Bias tensor of shape [3 * hidden_dim]
        num_heads: Number of attention heads

    Returns:
        Tuple of (q, k, v) tensors, each with shape [batch, num_heads, seq_len, head_dim]
        where q is scaled by 1/sqrt(head_dim)
    """
    logger.debug("GEMS _TRANSFORM_BIAS_RESCALE_QKV")

    # The kernel reads the bias with a unit stride, so a non-contiguous bias
    # would silently produce garbage. Route it through the FlagGems contiguous
    # op to guarantee the layout the kernel assumes.
    qkv_bias = contiguous(qkv_bias)

    batch, seq_len, total_dim = qkv.shape
    hidden_dim = total_dim // 3
    head_dim = hidden_dim // num_heads

    # Create output tensors
    q = torch.empty(
        (batch, num_heads, seq_len, head_dim),
        dtype=qkv.dtype,
        device=qkv.device,
    )
    k = torch.empty(
        (batch, num_heads, seq_len, head_dim),
        dtype=qkv.dtype,
        device=qkv.device,
    )
    v = torch.empty(
        (batch, num_heads, seq_len, head_dim),
        dtype=qkv.dtype,
        device=qkv.device,
    )

    # Calculate scaling factor for queries
    scale_factor = 1.0 / (head_dim**0.5)

    # Launch kernel
    total_elements = batch * num_heads * seq_len * head_dim
    grid = lambda meta: (triton.cdiv(total_elements, meta["BLOCK_SIZE"]),)

    with torch_device_fn.device(qkv.device):
        _transform_bias_rescale_qkv_kernel[grid](
            qkv,
            qkv_bias,
            q,
            k,
            v,
            batch,
            seq_len,
            num_heads,
            head_dim,
            scale_factor,
            qkv.stride(0),
            qkv.stride(1),
            qkv.stride(2),
            q.stride(0),
            q.stride(1),
            q.stride(2),
            q.stride(3),
            BLOCK_SIZE=1024,
        )

    return q, k, v
