# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl
from torch import Tensor

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


def _backward_heuristics():
    heuristics = dict(runtime.get_heuristic_config("batch_norm"))
    if runtime.device.vendor_name == "ascend":
        # The strided 3-D channels-last tile needs additional compiler buffers
        # on CANN 8.5; cap this operator's tile without changing other BN ops.
        heuristics["BLOCK_M"] = lambda args: min(
            8, triton.next_power_of_2(args["batch_dim"])
        )
        heuristics["BLOCK_N"] = lambda args: min(
            triton.next_power_of_2(args["spatial_dim"]),
            max(1, 256 // min(8, triton.next_power_of_2(args["batch_dim"]))),
        )
    return heuristics


def make_3d_for_bn(input: Tensor) -> Tensor:
    """
    Converts the input to a 3D view for batch normalization.

    Args:
        input: Input to render 3D.

    Returns:
        Input's 3D view.
    """
    if input.ndim == 2:
        input = input.unsqueeze(-1)

    elif input.ndim >= 4:
        input = input.flatten(2, -1)

    return input


@libentry()
@triton.autotune(
    configs=runtime.get_tuned_config("batch_norm"),
    key=["batch_dim", "spatial_dim"],
)
@triton.heuristics(_backward_heuristics())
@triton.jit
def cudnn_batch_norm_backward_kernel(
    grad_output_pointer,
    input_pointer,
    weight_pointer,
    mean_pointer,
    var_pointer,
    input_grad_pointer,
    weight_grad_pointer,
    bias_grad_pointer,
    batch_dim,
    spatial_dim,
    grad_output_batch_stride,
    grad_output_feat_stride,
    grad_output_spatial_stride,
    input_batch_stride,
    input_feat_stride,
    input_spatial_stride,
    input_grad_batch_stride,
    input_grad_feat_stride,
    input_grad_spatial_stride,
    eps,
    input_grad_mask: tl.constexpr,
    weight_grad_mask: tl.constexpr,
    bias_grad_mask: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    feat_pid = tl.program_id(axis=0)

    acc: tl.constexpr = (
        tl.float64 if input_pointer.dtype.element_ty == tl.float64 else tl.float32
    )
    mean = tl.load(feat_pid + mean_pointer).to(acc)
    inv_std = tl.load(feat_pid + var_pointer).to(acc)

    term1 = tl.zeros([BLOCK_M, BLOCK_N], dtype=acc)
    term2 = tl.zeros([BLOCK_M, BLOCK_N], dtype=acc)

    for m_step in range(0, tl.cdiv(batch_dim, BLOCK_M)):
        for n_step in range(0, tl.cdiv(spatial_dim, BLOCK_N)):
            batch_offset = m_step * BLOCK_M + tl.arange(0, BLOCK_M)
            batch_mask = batch_offset < batch_dim

            spatial_offset = n_step * BLOCK_N + tl.arange(0, BLOCK_N)
            spatial_mask = spatial_offset < spatial_dim

            curr_grad_output_pointer = (
                grad_output_pointer
                + grad_output_feat_stride * feat_pid
                + grad_output_batch_stride * batch_offset[:, None]
                + grad_output_spatial_stride * spatial_offset[None, :]
            )
            curr_input_pointer = (
                input_pointer
                + input_feat_stride * feat_pid
                + input_batch_stride * batch_offset[:, None]
                + input_spatial_stride * spatial_offset[None, :]
            )

            mask = batch_mask[:, None] & spatial_mask[None, :]
            curr_input = tl.load(curr_input_pointer, mask=mask, other=0).to(acc)

            curr_norm = (curr_input - mean) * inv_std
            curr_grad_output = tl.load(curr_grad_output_pointer, mask=mask, other=0).to(
                acc
            )

            term1 += tl.where(mask, curr_norm * curr_grad_output, 0)
            term2 += curr_grad_output

    term1 = tl.sum(term1)
    term2 = tl.sum(term2)

    if weight_grad_mask:
        tl.store(feat_pid + weight_grad_pointer, term1)
    if bias_grad_mask:
        tl.store(feat_pid + bias_grad_pointer, term2)

    if not input_grad_mask:
        return

    weight = tl.load(feat_pid + weight_pointer).to(acc)

    count = batch_dim * spatial_dim

    for m_step in range(0, tl.cdiv(batch_dim, BLOCK_M)):
        for n_step in range(0, tl.cdiv(spatial_dim, BLOCK_N)):
            batch_offset = m_step * BLOCK_M + tl.arange(0, BLOCK_M)
            batch_mask = batch_offset < batch_dim

            spatial_offset = n_step * BLOCK_N + tl.arange(0, BLOCK_N)
            spatial_mask = spatial_offset < spatial_dim

            curr_grad_output_pointer = (
                grad_output_pointer
                + grad_output_feat_stride * feat_pid
                + grad_output_batch_stride * batch_offset[:, None]
                + grad_output_spatial_stride * spatial_offset[None, :]
            )
            curr_input_pointer = (
                input_pointer
                + input_feat_stride * feat_pid
                + input_batch_stride * batch_offset[:, None]
                + input_spatial_stride * spatial_offset[None, :]
            )
            curr_input_grad_pointer = (
                input_grad_pointer
                + input_grad_feat_stride * feat_pid
                + input_grad_batch_stride * batch_offset[:, None]
                + input_grad_spatial_stride * spatial_offset[None, :]
            )

            curr_input = tl.load(
                curr_input_pointer, mask=batch_mask[:, None] & spatial_mask[None, :]
            ).to(acc)
            curr_norm = (curr_input - mean) * inv_std
            curr_grad_output = tl.load(
                curr_grad_output_pointer,
                mask=batch_mask[:, None] & spatial_mask[None, :],
            ).to(acc)
            curr_input_grad = (
                inv_std
                * weight
                * (curr_grad_output - (term1 * curr_norm + term2) / count)
            )
            tl.store(
                curr_input_grad_pointer,
                curr_input_grad,
                mask=batch_mask[:, None] & spatial_mask[None, :],
            )


def cudnn_batch_norm_backward(
    input: Tensor,
    grad_output: Tensor,
    weight: Tensor,
    running_mean: Tensor = None,
    running_var: Tensor = None,
    save_mean: Tensor = None,
    save_var: Tensor = None,
    epsilon: float = 1e-5,
    reserveSpace: Tensor = None,
):
    logger.debug("GEMS CUDNN_BATCH_NORM_BACKWARD")
    if input.ndim < 2 or input.ndim > 5 or input.numel() == 0:
        raise RuntimeError(
            "cudnn_batch_norm_backward requires a nonempty rank 2 through 5 input"
        )
    if (
        grad_output.shape != input.shape
        or grad_output.dtype != input.dtype
        or grad_output.device != input.device
    ):
        raise RuntimeError("grad_output must match input shape, dtype and device")
    param_dtype = torch.float32 if input.dtype == torch.float16 else input.dtype
    if input.dtype not in (torch.float16, torch.float32, torch.float64):
        raise RuntimeError("unsupported cudnn_batch_norm_backward input dtype")
    for t in (weight, save_mean, save_var):
        if (
            t is None
            or t.numel() != input.shape[1]
            or t.dtype != param_dtype
            or t.device != input.device
            or not t.is_contiguous()
        ):
            raise RuntimeError(
                "weight and saved statistics must be contiguous C-element tensors with the parameter dtype"
            )

    input_3d = make_3d_for_bn(input)
    grad_output_3d = make_3d_for_bn(grad_output)

    batch_dim, feat_dim, spatial_dim = input_3d.shape

    # Always compute all gradients
    input_grad = torch.empty_like(input_3d)
    weight_grad = torch.empty_like(weight)
    bias_grad = torch.empty_like(weight)

    # Launches 1D grid where each program operates over one feature.
    with torch_device_fn.device(input.device):
        if (
            runtime.device.vendor_name == "nvidia"
            and input.dtype == torch.float64
            and input_3d.is_contiguous()
            and grad_output_3d.is_contiguous()
        ):
            from flag_gems.runtime.backend._nvidia.ops._cudnn_batch_norm_backward import (
                _backward_apply,
                _backward_fused,
                _backward_partial,
            )

            count = batch_dim * spatial_dim
            if count <= 2048:
                _backward_fused[(feat_dim,)](
                    input_3d,
                    grad_output_3d,
                    weight,
                    save_mean,
                    save_var,
                    input_grad,
                    weight_grad,
                    bias_grad,
                    count,
                    feat_dim,
                    spatial_dim,
                    triton.next_power_of_2(count),
                )
            else:
                parts = triton.cdiv(count, 1024)
                partial = torch.empty(
                    (feat_dim, 2, parts), dtype=input.dtype, device=input.device
                )
                _backward_partial[(feat_dim, parts)](
                    input_3d,
                    grad_output_3d,
                    save_mean,
                    partial,
                    count,
                    feat_dim,
                    spatial_dim,
                    parts,
                    1024,
                )
                _backward_apply[(feat_dim, parts)](
                    input_3d,
                    grad_output_3d,
                    weight,
                    save_mean,
                    save_var,
                    partial,
                    input_grad,
                    weight_grad,
                    bias_grad,
                    count,
                    feat_dim,
                    spatial_dim,
                    parts,
                    triton.next_power_of_2(parts),
                    1024,
                )
            return input_grad.view_as(input), weight_grad, bias_grad
        cudnn_batch_norm_backward_kernel[(feat_dim,)](
            grad_output_3d,
            input_3d,
            weight,
            save_mean,
            save_var,  # Saved inverse standard deviation
            input_grad,
            weight_grad,
            bias_grad,
            batch_dim,
            spatial_dim,
            *grad_output_3d.stride(),
            *input_3d.stride(),
            *input_grad.stride(),
            epsilon,  # eps
            True,  # input_grad_mask
            True,  # weight_grad_mask
            True,  # bias_grad_mask
        )

    return (
        input_grad.view_as(input),
        weight_grad,
        bias_grad,
    )
