# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
"""FlagGems Triton implementation of aten::_cudnn_rnn.

Every code path runs on Triton kernels: the recurrent kernels, packed
sequences, and inter-layer dropout (via ``flag_gems.dropout``).
"""

import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.ops.dropout import dropout
from flag_gems.ops.flip import flip
from flag_gems.utils import libentry, tl_extra_shim

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# RNN mode constants
# ---------------------------------------------------------------------------
_RNN_RELU = 0
_RNN_TANH = 1
_LSTM = 2
_GRU = 3

_WS_NB = 2
_WS_B = 4
_WS_NBP = 3
_WS_BP = 5


# ===================================================================
#  Triton helpers
# ===================================================================


@triton.jit
def _init_hidden(
    scratch_ptr, hx_ptr, batch_idx, hidden_out, num_blocks, BLOCK_SIZE: tl.constexpr
):
    bid_offs = tl.arange(0, BLOCK_SIZE)
    for blk in range(num_blocks):
        offs = blk * BLOCK_SIZE + bid_offs
        mask = offs < hidden_out
        val = tl.load(hx_ptr + batch_idx * hidden_out + offs, mask=mask, other=0.0).to(
            tl.float32
        )
        tl.store(scratch_ptr + batch_idx * hidden_out + offs, val, mask=mask)


@triton.jit
def _init_cell(
    scratch_ptr, cx_ptr, batch_idx, hidden_size, num_blocks, BLOCK_SIZE: tl.constexpr
):
    bid_offs = tl.arange(0, BLOCK_SIZE)
    for blk in range(num_blocks):
        offs = blk * BLOCK_SIZE + bid_offs
        mask = offs < hidden_size
        val = tl.load(cx_ptr + batch_idx * hidden_size + offs, mask=mask, other=0.0).to(
            tl.float32
        )
        tl.store(scratch_ptr + batch_idx * hidden_size + offs, val, mask=mask)


# ===================================================================
#  Kernel: RNN (relu / tanh)  — uniform batch
# ===================================================================


@libentry()
@triton.jit
def _rnn_kernel(
    input_ptr,
    hx_ptr,
    weight_ih_ptr,
    weight_hh_ptr,
    bias_ih_ptr,
    bias_hh_ptr,
    output_ptr,
    hy_ptr,
    h_scratch_ptr,
    h_read_ptr,
    seq_len,
    batch_size,
    input_dim,
    hidden_out,
    batch_first: tl.constexpr,
    nonlinearity: tl.constexpr,  # 0=relu, 1=tanh
    has_bias: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Single-layer RNN (relu/tanh) — uniform batch.

    Grid: ``(batch_size,)``.
    """
    batch_idx = tl.program_id(0)
    if batch_idx >= batch_size:
        return

    CHUNK: tl.constexpr = 64
    num_hid_blocks = tl.cdiv(hidden_out, BLOCK_SIZE)
    chunk_offs = tl.arange(0, CHUNK)
    bid_offs = tl.arange(0, BLOCK_SIZE)

    _init_hidden(
        h_scratch_ptr, hx_ptr, batch_idx, hidden_out, num_hid_blocks, BLOCK_SIZE
    )

    if batch_first:
        batch_inp_stride = seq_len * input_dim
        batch_out_stride = seq_len * hidden_out
    else:
        batch_inp_stride = input_dim
        batch_out_stride = hidden_out

    h_scratch_base = h_scratch_ptr + batch_idx * hidden_out
    h_read_base = h_read_ptr + batch_idx * hidden_out

    for t in range(seq_len):
        if batch_first:
            t_inp_off = batch_idx * batch_inp_stride + t * input_dim
            t_out_off = batch_idx * batch_out_stride + t * hidden_out
        else:
            t_inp_off = t * (batch_size * input_dim) + batch_idx * input_dim
            t_out_off = t * (batch_size * hidden_out) + batch_idx * hidden_out

        # double-buffer snapshot
        for hid_block in range(num_hid_blocks):
            offs = hid_block * BLOCK_SIZE + bid_offs
            mask = offs < hidden_out
            val = tl.load(h_scratch_base + offs, mask=mask, other=0.0)
            tl.store(h_read_base + offs, val, mask=mask)
        # h_read is read by other warps below; fence the stores first.
        tl.debug_barrier()

        # ---- mat-vec + activation ----
        for hid_block in range(num_hid_blocks):
            h_start = hid_block * BLOCK_SIZE
            h_offs = h_start + bid_offs
            h_mask = h_offs < hidden_out

            # W_ih @ x_t + b_ih
            ih_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            for inp_start in range(0, input_dim, CHUNK):
                i_offs = inp_start + chunk_offs
                i_mask = i_offs < input_dim
                w_offs = h_offs[:, None] * input_dim + i_offs[None, :]
                w_mask = h_mask[:, None] & i_mask[None, :]
                w_tile = tl.load(weight_ih_ptr + w_offs, mask=w_mask, other=0.0).to(
                    tl.float32
                )
                x_tile = tl.load(
                    input_ptr + t_inp_off + i_offs, mask=i_mask, other=0.0
                ).to(tl.float32)
                ih_acc += tl.sum(w_tile * x_tile[None, :], axis=1)
            if has_bias:
                ih_acc += tl.load(bias_ih_ptr + h_offs, mask=h_mask, other=0.0).to(
                    tl.float32
                )

            # W_hh @ h_prev + b_hh
            hh_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            for hid_in_start in range(0, hidden_out, CHUNK):
                j_offs = hid_in_start + chunk_offs
                j_mask = j_offs < hidden_out
                w_offs = h_offs[:, None] * hidden_out + j_offs[None, :]
                w_mask = h_mask[:, None] & j_mask[None, :]
                w_tile = tl.load(weight_hh_ptr + w_offs, mask=w_mask, other=0.0).to(
                    tl.float32
                )
                h_tile = tl.load(h_read_base + j_offs, mask=j_mask, other=0.0).to(
                    tl.float32
                )
                hh_acc += tl.sum(w_tile * h_tile[None, :], axis=1)
            if has_bias:
                hh_acc += tl.load(bias_hh_ptr + h_offs, mask=h_mask, other=0.0).to(
                    tl.float32
                )

            h_new = ih_acc + hh_acc
            if nonlinearity == 0:
                h_new = tl.where(h_new > 0, h_new, 0.0)
            else:
                h_new = tl_extra_shim.tanh(h_new)

            tl.store(output_ptr + t_out_off + h_offs, h_new, mask=h_mask)
            tl.store(h_scratch_base + h_offs, h_new, mask=h_mask)

    # final hidden → hy
    for hid_block in range(num_hid_blocks):
        offs = hid_block * BLOCK_SIZE + bid_offs
        mask = offs < hidden_out
        tl.store(
            hy_ptr + batch_idx * hidden_out + offs,
            tl.load(h_scratch_base + offs, mask=mask, other=0.0),
            mask=mask,
        )


# ===================================================================
#  Kernel: RNN (relu / tanh)  — packed sequences
# ===================================================================


@libentry()
@triton.jit
def _rnn_packed_kernel(
    input_ptr,
    hx_ptr,
    weight_ih_ptr,
    weight_hh_ptr,
    bias_ih_ptr,
    bias_hh_ptr,
    output_ptr,
    hy_ptr,
    h_scratch_ptr,
    h_read_ptr,
    # packed-specific
    batch_sizes_ptr,  # int32 array [num_steps]
    input_offsets_ptr,  # int32 array [num_steps], cumulative offset
    output_offsets_ptr,  # int32 array [num_steps]
    num_steps,
    max_batch,
    input_dim,
    hidden_out,
    nonlinearity: tl.constexpr,
    has_bias: tl.constexpr,
    reverse: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Single-layer RNN — packed sequences.

    Grid: ``(max_batch,)``.  Each program processes one batch slot;
    silently skips time steps where ``pid >= batch_sizes[t]``.
    """
    pid = tl.program_id(0)
    if pid >= max_batch:
        return

    CHUNK: tl.constexpr = 64
    num_hid_blocks = tl.cdiv(hidden_out, BLOCK_SIZE)
    chunk_offs = tl.arange(0, CHUNK)
    bid_offs = tl.arange(0, BLOCK_SIZE)

    _init_hidden(h_scratch_ptr, hx_ptr, pid, hidden_out, num_hid_blocks, BLOCK_SIZE)

    h_scratch_base = h_scratch_ptr + pid * hidden_out
    h_read_base = h_read_ptr + pid * hidden_out

    for t_loop in range(num_steps):
        t = num_steps - 1 - t_loop if reverse else t_loop
        cur_bs = tl.load(batch_sizes_ptr + t).to(tl.int32)

        inp_offset = tl.load(input_offsets_ptr + t).to(tl.int32)
        out_offset = tl.load(output_offsets_ptr + t).to(tl.int32)
        t_inp_off = inp_offset + pid
        t_out_off = out_offset + pid

        # double-buffer snapshot
        for hid_block in range(num_hid_blocks):
            offs = hid_block * BLOCK_SIZE + bid_offs
            mask = offs < hidden_out
            val = tl.load(h_scratch_base + offs, mask=mask, other=0.0)
            tl.store(h_read_base + offs, val, mask=mask)
        # h_read is read by other warps below; fence the stores first.
        tl.debug_barrier()

        # Only compute & store if this batch slot is active at this time step.
        for hid_block in range(num_hid_blocks):
            h_start = hid_block * BLOCK_SIZE
            h_offs = h_start + bid_offs
            h_mask = h_offs < hidden_out

            ih_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            for inp_start in range(0, input_dim, CHUNK):
                i_offs = inp_start + chunk_offs
                i_mask = i_offs < input_dim
                w_offs = h_offs[:, None] * input_dim + i_offs[None, :]
                w_mask = h_mask[:, None] & i_mask[None, :]
                w_tile = tl.load(weight_ih_ptr + w_offs, mask=w_mask, other=0.0).to(
                    tl.float32
                )
                x_tile = tl.load(
                    input_ptr + t_inp_off * input_dim + i_offs,
                    mask=i_mask & (pid < cur_bs),
                    other=0.0,
                ).to(tl.float32)
                ih_acc += tl.sum(w_tile * x_tile[None, :], axis=1)
            if has_bias:
                ih_acc += tl.load(bias_ih_ptr + h_offs, mask=h_mask, other=0.0).to(
                    tl.float32
                )

            hh_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            for hid_in_start in range(0, hidden_out, CHUNK):
                j_offs = hid_in_start + chunk_offs
                j_mask = j_offs < hidden_out
                w_offs = h_offs[:, None] * hidden_out + j_offs[None, :]
                w_mask = h_mask[:, None] & j_mask[None, :]
                w_tile = tl.load(weight_hh_ptr + w_offs, mask=w_mask, other=0.0).to(
                    tl.float32
                )
                h_tile = tl.load(h_read_base + j_offs, mask=j_mask, other=0.0).to(
                    tl.float32
                )
                hh_acc += tl.sum(w_tile * h_tile[None, :], axis=1)
            if has_bias:
                hh_acc += tl.load(bias_hh_ptr + h_offs, mask=h_mask, other=0.0).to(
                    tl.float32
                )

            gate = ih_acc + hh_acc
            if nonlinearity == 0:
                h_new = tl.where(gate > 0, gate, 0.0)
            else:
                h_new = tl_extra_shim.tanh(gate)

            # Only write when this batch slot is active.
            store_mask = h_mask & (pid < cur_bs)
            tl.store(
                output_ptr + t_out_off * hidden_out + h_offs, h_new, mask=store_mask
            )

            # Conditional scratch update: keep old value if not active.
            old_h = tl.load(h_scratch_base + h_offs, mask=h_mask, other=0.0)
            merged = tl.where(pid < cur_bs, h_new, old_h)
            tl.store(h_scratch_base + h_offs, merged, mask=h_mask)

    # final hidden → hy
    for hid_block in range(num_hid_blocks):
        offs = hid_block * BLOCK_SIZE + bid_offs
        mask = offs < hidden_out
        tl.store(
            hy_ptr + pid * hidden_out + offs,
            tl.load(h_scratch_base + offs, mask=mask, other=0.0),
            mask=mask,
        )


# ===================================================================
#  Kernel: LSTM  — uniform batch
# ===================================================================


@libentry()
@triton.jit
def _lstm_kernel(
    input_ptr,
    hx_ptr,
    cx_ptr,
    weight_ih_ptr,
    weight_hh_ptr,
    w_hr_ptr,
    bias_ih_ptr,
    bias_hh_ptr,
    output_ptr,
    hy_ptr,
    cy_ptr,
    h_scratch_ptr,
    h_read_ptr,
    h_proj_ptr,
    c_scratch_ptr,
    seq_len,
    batch_size,
    input_dim,
    hidden_size,
    proj_size,
    batch_first: tl.constexpr,
    has_bias: tl.constexpr,
    has_proj: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Single-layer LSTM — uniform batch.  Grid: ``(batch_size,)``."""
    batch_idx = tl.program_id(0)
    if batch_idx >= batch_size:
        return

    CHUNK: tl.constexpr = 64
    hidden_out = proj_size if has_proj else hidden_size
    num_cell_blocks = tl.cdiv(hidden_size, BLOCK_SIZE)
    chunk_offs = tl.arange(0, CHUNK)
    bid_offs = tl.arange(0, BLOCK_SIZE)

    _init_hidden(
        h_scratch_ptr,
        hx_ptr,
        batch_idx,
        hidden_out,
        tl.cdiv(hidden_out, BLOCK_SIZE),
        BLOCK_SIZE,
    )
    _init_cell(
        c_scratch_ptr, cx_ptr, batch_idx, hidden_size, num_cell_blocks, BLOCK_SIZE
    )

    if batch_first:
        batch_inp_stride = seq_len * input_dim
        batch_out_stride = seq_len * hidden_out
    else:
        batch_inp_stride = input_dim
        batch_out_stride = hidden_out

    h_scratch_base = h_scratch_ptr + batch_idx * hidden_out
    h_read_base = h_read_ptr + batch_idx * hidden_out
    h_proj_base = h_proj_ptr + batch_idx * hidden_size
    c_scratch_base = c_scratch_ptr + batch_idx * hidden_size

    for t in range(seq_len):
        if batch_first:
            t_inp_off = batch_idx * batch_inp_stride + t * input_dim
            t_out_off = batch_idx * batch_out_stride + t * hidden_out
        else:
            t_inp_off = t * (batch_size * input_dim) + batch_idx * input_dim
            t_out_off = t * (batch_size * hidden_out) + batch_idx * hidden_out

        # double-buffer snapshot
        for hid_block in range(tl.cdiv(hidden_out, BLOCK_SIZE)):
            offs = hid_block * BLOCK_SIZE + bid_offs
            mask = offs < hidden_out
            tl.store(
                h_read_base + offs,
                tl.load(h_scratch_base + offs, mask=mask, other=0.0),
                mask=mask,
            )
        # h_read is read by other warps below; fence the stores first.
        tl.debug_barrier()

        # ---- step 1: compute LSTM gates per hidden_size block ----
        for cell_block in range(num_cell_blocks):
            cell_start = cell_block * BLOCK_SIZE
            c_offs = cell_start + bid_offs
            c_mask = c_offs < hidden_size
            cell_val = tl.load(c_scratch_base + c_offs, mask=c_mask, other=0.0).to(
                tl.float32
            )

            i_gate = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            f_gate = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            g_gate = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            o_gate = tl.zeros([BLOCK_SIZE], dtype=tl.float32)

            for gate_idx in tl.static_range(4):
                gate_offs = cell_start + gate_idx * hidden_size + bid_offs
                gate_mask = (cell_start + bid_offs) < hidden_size

                # ---- ih ----
                ih_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
                for inp_start in range(0, input_dim, CHUNK):
                    i_offs = inp_start + chunk_offs
                    i_mask = i_offs < input_dim
                    w_offs = gate_offs[:, None] * input_dim + i_offs[None, :]
                    w_mask = gate_mask[:, None] & i_mask[None, :]
                    w_tile = tl.load(weight_ih_ptr + w_offs, mask=w_mask, other=0.0).to(
                        tl.float32
                    )
                    x_tile = tl.load(
                        input_ptr + t_inp_off + i_offs, mask=i_mask, other=0.0
                    ).to(tl.float32)
                    ih_acc += tl.sum(w_tile * x_tile[None, :], axis=1)
                if has_bias:
                    ih_acc += tl.load(
                        bias_ih_ptr + gate_offs, mask=gate_mask, other=0.0
                    ).to(tl.float32)

                # ---- hh ----
                hh_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
                for hid_in_start in range(0, hidden_out, CHUNK):
                    j_offs = hid_in_start + chunk_offs
                    j_mask = j_offs < hidden_out
                    w_offs = gate_offs[:, None] * hidden_out + j_offs[None, :]
                    w_mask = gate_mask[:, None] & j_mask[None, :]
                    w_tile = tl.load(weight_hh_ptr + w_offs, mask=w_mask, other=0.0).to(
                        tl.float32
                    )
                    h_tile = tl.load(h_read_base + j_offs, mask=j_mask, other=0.0).to(
                        tl.float32
                    )
                    hh_acc += tl.sum(w_tile * h_tile[None, :], axis=1)
                if has_bias:
                    hh_acc += tl.load(
                        bias_hh_ptr + gate_offs, mask=gate_mask, other=0.0
                    ).to(tl.float32)

                gate = ih_acc + hh_acc
                if gate_idx == 0:
                    i_gate = tl.sigmoid(gate)
                elif gate_idx == 1:
                    f_gate = tl.sigmoid(gate)
                elif gate_idx == 2:
                    g_gate = tl_extra_shim.tanh(gate)
                else:
                    o_gate = tl.sigmoid(gate)

            c_new = f_gate * cell_val + i_gate * g_gate
            h_raw = o_gate * tl_extra_shim.tanh(c_new)

            tl.store(c_scratch_base + c_offs, c_new, mask=c_mask)

            if not has_proj:
                tl.store(
                    output_ptr + t_out_off + cell_start + bid_offs, h_raw, mask=c_mask
                )
                tl.store(h_scratch_base + cell_start + bid_offs, h_raw, mask=c_mask)
            else:
                # keep the raw h for the projection step; h_scratch holds the
                # projected values and h_read the recurrent snapshot, so the
                # raw h needs its own buffer
                tl.store(h_proj_base + cell_start + bid_offs, h_raw, mask=c_mask)
        # the gate loop writes h_proj, read by the projection step below.
        if has_proj:
            tl.debug_barrier()

        # ---- step 2: projection ----
        if has_proj:
            for proj_block in range(tl.cdiv(proj_size, BLOCK_SIZE)):
                p_start = proj_block * BLOCK_SIZE
                p_offs = p_start + bid_offs
                p_mask = p_offs < proj_size

                proj_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
                for hid_in_start in range(0, hidden_size, CHUNK):
                    j_offs = hid_in_start + chunk_offs
                    j_mask = j_offs < hidden_size
                    w_offs = p_offs[:, None] * hidden_size + j_offs[None, :]
                    w_mask = p_mask[:, None] & j_mask[None, :]
                    w_tile = tl.load(w_hr_ptr + w_offs, mask=w_mask, other=0.0).to(
                        tl.float32
                    )
                    h_tile = tl.load(h_proj_base + j_offs, mask=j_mask, other=0.0).to(
                        tl.float32
                    )
                    proj_acc += tl.sum(w_tile * h_tile[None, :], axis=1)

                tl.store(
                    output_ptr + t_out_off + p_start + bid_offs, proj_acc, mask=p_mask
                )
                tl.store(h_scratch_base + p_start + bid_offs, proj_acc, mask=p_mask)

    # final → hy, cy
    for hid_block in range(tl.cdiv(hidden_out, BLOCK_SIZE)):
        offs = hid_block * BLOCK_SIZE + bid_offs
        mask = offs < hidden_out
        tl.store(
            hy_ptr + batch_idx * hidden_out + offs,
            tl.load(h_scratch_base + offs, mask=mask, other=0.0),
            mask=mask,
        )
    for cell_block in range(num_cell_blocks):
        offs = cell_block * BLOCK_SIZE + bid_offs
        mask = offs < hidden_size
        tl.store(
            cy_ptr + batch_idx * hidden_size + offs,
            tl.load(c_scratch_base + offs, mask=mask, other=0.0),
            mask=mask,
        )


# ===================================================================
#  Kernel: LSTM  — packed sequences
# ===================================================================


@libentry()
@triton.jit
def _lstm_packed_kernel(
    input_ptr,
    hx_ptr,
    cx_ptr,
    weight_ih_ptr,
    weight_hh_ptr,
    w_hr_ptr,
    bias_ih_ptr,
    bias_hh_ptr,
    output_ptr,
    hy_ptr,
    cy_ptr,
    h_scratch_ptr,
    h_read_ptr,
    h_proj_ptr,
    c_scratch_ptr,
    batch_sizes_ptr,
    input_offsets_ptr,
    output_offsets_ptr,
    num_steps,
    max_batch,
    input_dim,
    hidden_size,
    proj_size,
    has_bias: tl.constexpr,
    has_proj: tl.constexpr,
    reverse: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Single-layer LSTM — packed sequences.  Grid: ``(max_batch,)``."""
    pid = tl.program_id(0)
    if pid >= max_batch:
        return

    CHUNK: tl.constexpr = 64
    hidden_out = proj_size if has_proj else hidden_size
    num_cell_blocks = tl.cdiv(hidden_size, BLOCK_SIZE)
    chunk_offs = tl.arange(0, CHUNK)
    bid_offs = tl.arange(0, BLOCK_SIZE)

    _init_hidden(
        h_scratch_ptr,
        hx_ptr,
        pid,
        hidden_out,
        tl.cdiv(hidden_out, BLOCK_SIZE),
        BLOCK_SIZE,
    )
    _init_cell(c_scratch_ptr, cx_ptr, pid, hidden_size, num_cell_blocks, BLOCK_SIZE)

    h_scratch_base = h_scratch_ptr + pid * hidden_out
    h_read_base = h_read_ptr + pid * hidden_out
    h_proj_base = h_proj_ptr + pid * hidden_size
    c_scratch_base = c_scratch_ptr + pid * hidden_size

    for t_loop in range(num_steps):
        t = num_steps - 1 - t_loop if reverse else t_loop
        cur_bs = tl.load(batch_sizes_ptr + t).to(tl.int32)

        inp_offset = tl.load(input_offsets_ptr + t).to(tl.int32)
        out_offset = tl.load(output_offsets_ptr + t).to(tl.int32)
        t_inp_off = inp_offset + pid
        t_out_off = out_offset + pid
        active = pid < cur_bs

        # double-buffer snapshot
        for hid_block in range(tl.cdiv(hidden_out, BLOCK_SIZE)):
            offs = hid_block * BLOCK_SIZE + bid_offs
            mask = offs < hidden_out
            tl.store(
                h_read_base + offs,
                tl.load(h_scratch_base + offs, mask=mask, other=0.0),
                mask=mask,
            )
        # h_read is read by other warps below; fence the stores first.
        tl.debug_barrier()

        # ---- gates ----
        for cell_block in range(num_cell_blocks):
            cell_start = cell_block * BLOCK_SIZE
            c_offs = cell_start + bid_offs
            c_mask = c_offs < hidden_size
            cell_val = tl.load(c_scratch_base + c_offs, mask=c_mask, other=0.0).to(
                tl.float32
            )

            i_gate = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            f_gate = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            g_gate = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            o_gate = tl.zeros([BLOCK_SIZE], dtype=tl.float32)

            for gate_idx in tl.static_range(4):
                gate_offs = cell_start + gate_idx * hidden_size + bid_offs
                gate_mask = (cell_start + bid_offs) < hidden_size

                ih_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
                for inp_start in range(0, input_dim, CHUNK):
                    i_offs = inp_start + chunk_offs
                    i_mask = i_offs < input_dim
                    w_offs = gate_offs[:, None] * input_dim + i_offs[None, :]
                    w_mask = gate_mask[:, None] & i_mask[None, :]
                    w_tile = tl.load(weight_ih_ptr + w_offs, mask=w_mask, other=0.0).to(
                        tl.float32
                    )
                    x_tile = tl.load(
                        input_ptr + t_inp_off * input_dim + i_offs,
                        mask=i_mask & active,
                        other=0.0,
                    ).to(tl.float32)
                    ih_acc += tl.sum(w_tile * x_tile[None, :], axis=1)
                if has_bias:
                    ih_acc += tl.load(
                        bias_ih_ptr + gate_offs, mask=gate_mask, other=0.0
                    ).to(tl.float32)

                hh_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
                for hid_in_start in range(0, hidden_out, CHUNK):
                    j_offs = hid_in_start + chunk_offs
                    j_mask = j_offs < hidden_out
                    w_offs = gate_offs[:, None] * hidden_out + j_offs[None, :]
                    w_mask = gate_mask[:, None] & j_mask[None, :]
                    w_tile = tl.load(weight_hh_ptr + w_offs, mask=w_mask, other=0.0).to(
                        tl.float32
                    )
                    h_tile = tl.load(h_read_base + j_offs, mask=j_mask, other=0.0).to(
                        tl.float32
                    )
                    hh_acc += tl.sum(w_tile * h_tile[None, :], axis=1)
                if has_bias:
                    hh_acc += tl.load(
                        bias_hh_ptr + gate_offs, mask=gate_mask, other=0.0
                    ).to(tl.float32)

                gate = ih_acc + hh_acc
                if gate_idx == 0:
                    i_gate = tl.sigmoid(gate)
                elif gate_idx == 1:
                    f_gate = tl.sigmoid(gate)
                elif gate_idx == 2:
                    g_gate = tl_extra_shim.tanh(gate)
                else:
                    o_gate = tl.sigmoid(gate)

            c_new = f_gate * cell_val + i_gate * g_gate
            h_raw = o_gate * tl_extra_shim.tanh(c_new)

            # conditional cell state update
            old_c = tl.load(c_scratch_base + c_offs, mask=c_mask, other=0.0).to(
                tl.float32
            )
            c_final = tl.where(active, c_new, old_c)
            tl.store(c_scratch_base + c_offs, c_final, mask=c_mask)

            store_mask = c_mask & active
            if not has_proj:
                tl.store(
                    output_ptr + t_out_off * hidden_out + cell_start + bid_offs,
                    h_raw,
                    mask=store_mask,
                )
                # conditional hidden update
                old_h = tl.load(
                    h_scratch_base + cell_start + bid_offs, mask=c_mask, other=0.0
                )
                h_final = tl.where(active, h_raw, old_h)
                tl.store(h_scratch_base + cell_start + bid_offs, h_final, mask=c_mask)
            else:
                # keep the raw h for the projection step; h_scratch holds the
                # projected values and h_read the recurrent snapshot, so the
                # raw h needs its own buffer
                old_h = tl.load(
                    h_scratch_base + cell_start + bid_offs, mask=c_mask, other=0.0
                )
                h_final = tl.where(active, h_raw, old_h)
                tl.store(h_proj_base + cell_start + bid_offs, h_final, mask=c_mask)
        # the gate loop writes h_proj, read by the projection step below.
        if has_proj:
            tl.debug_barrier()

        if has_proj:
            for proj_block in range(tl.cdiv(proj_size, BLOCK_SIZE)):
                p_start = proj_block * BLOCK_SIZE
                p_offs = p_start + bid_offs
                p_mask = p_offs < proj_size

                proj_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
                for hid_in_start in range(0, hidden_size, CHUNK):
                    j_offs = hid_in_start + chunk_offs
                    j_mask = j_offs < hidden_size
                    w_offs = p_offs[:, None] * hidden_size + j_offs[None, :]
                    w_mask = p_mask[:, None] & j_mask[None, :]
                    w_tile = tl.load(w_hr_ptr + w_offs, mask=w_mask, other=0.0).to(
                        tl.float32
                    )
                    h_tile = tl.load(h_proj_base + j_offs, mask=j_mask, other=0.0).to(
                        tl.float32
                    )
                    proj_acc += tl.sum(w_tile * h_tile[None, :], axis=1)

                store_mask = p_mask & active
                tl.store(
                    output_ptr + t_out_off * hidden_out + p_start + bid_offs,
                    proj_acc,
                    mask=store_mask,
                )
                old_p = tl.load(
                    h_scratch_base + p_start + bid_offs, mask=p_mask, other=0.0
                )
                p_final = tl.where(active, proj_acc, old_p)
                tl.store(h_scratch_base + p_start + bid_offs, p_final, mask=p_mask)

    # final → hy, cy
    for hid_block in range(tl.cdiv(hidden_out, BLOCK_SIZE)):
        offs = hid_block * BLOCK_SIZE + bid_offs
        mask = offs < hidden_out
        tl.store(
            hy_ptr + pid * hidden_out + offs,
            tl.load(h_scratch_base + offs, mask=mask, other=0.0),
            mask=mask,
        )
    for cell_block in range(num_cell_blocks):
        offs = cell_block * BLOCK_SIZE + bid_offs
        mask = offs < hidden_size
        tl.store(
            cy_ptr + pid * hidden_size + offs,
            tl.load(c_scratch_base + offs, mask=mask, other=0.0),
            mask=mask,
        )


# ===================================================================
#  Kernel: GRU  — uniform batch
# ===================================================================


@libentry()
@triton.jit
def _gru_kernel(
    input_ptr,
    hx_ptr,
    weight_ih_ptr,
    weight_hh_ptr,
    bias_ih_ptr,
    bias_hh_ptr,
    output_ptr,
    hy_ptr,
    h_scratch_ptr,
    h_read_ptr,
    seq_len,
    batch_size,
    input_dim,
    hidden_size,
    batch_first: tl.constexpr,
    has_bias: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Single-layer GRU — uniform batch.  Grid: ``(batch_size,)``."""
    batch_idx = tl.program_id(0)
    if batch_idx >= batch_size:
        return

    CHUNK: tl.constexpr = 64
    num_hid_blocks = tl.cdiv(hidden_size, BLOCK_SIZE)
    chunk_offs = tl.arange(0, CHUNK)
    bid_offs = tl.arange(0, BLOCK_SIZE)

    _init_hidden(
        h_scratch_ptr, hx_ptr, batch_idx, hidden_size, num_hid_blocks, BLOCK_SIZE
    )

    if batch_first:
        batch_inp_stride = seq_len * input_dim
        batch_out_stride = seq_len * hidden_size
    else:
        batch_inp_stride = input_dim
        batch_out_stride = hidden_size

    h_scratch_base = h_scratch_ptr + batch_idx * hidden_size
    h_read_base = h_read_ptr + batch_idx * hidden_size

    for t in range(seq_len):
        if batch_first:
            t_inp_off = batch_idx * batch_inp_stride + t * input_dim
            t_out_off = batch_idx * batch_out_stride + t * hidden_size
        else:
            t_inp_off = t * (batch_size * input_dim) + batch_idx * input_dim
            t_out_off = t * (batch_size * hidden_size) + batch_idx * hidden_size

        # double-buffer snapshot
        for hid_block in range(num_hid_blocks):
            offs = hid_block * BLOCK_SIZE + bid_offs
            mask = offs < hidden_size
            tl.store(
                h_read_base + offs,
                tl.load(h_scratch_base + offs, mask=mask, other=0.0),
                mask=mask,
            )
        # h_read is read by other warps below; fence the stores first.
        tl.debug_barrier()

        for hid_block in range(num_hid_blocks):
            h_start = hid_block * BLOCK_SIZE
            h_offs = h_start + bid_offs
            h_mask = h_offs < hidden_size

            r_i_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            z_i_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            n_i_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            r_h_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            z_h_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            n_h_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)

            for gate_idx in tl.static_range(3):
                gate_row = gate_idx * hidden_size + h_start + bid_offs
                gate_mask = (h_start + bid_offs) < hidden_size

                g_i_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
                for inp_start in range(0, input_dim, CHUNK):
                    i_offs = inp_start + chunk_offs
                    i_mask = i_offs < input_dim
                    w_offs = gate_row[:, None] * input_dim + i_offs[None, :]
                    w_mask = gate_mask[:, None] & i_mask[None, :]
                    w_tile = tl.load(weight_ih_ptr + w_offs, mask=w_mask, other=0.0).to(
                        tl.float32
                    )
                    x_tile = tl.load(
                        input_ptr + t_inp_off + i_offs, mask=i_mask, other=0.0
                    ).to(tl.float32)
                    g_i_acc += tl.sum(w_tile * x_tile[None, :], axis=1)
                if has_bias:
                    g_i_acc += tl.load(
                        bias_ih_ptr + gate_row, mask=gate_mask, other=0.0
                    ).to(tl.float32)

                g_h_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
                for hid_in_start in range(0, hidden_size, CHUNK):
                    j_offs = hid_in_start + chunk_offs
                    j_mask = j_offs < hidden_size
                    w_offs = gate_row[:, None] * hidden_size + j_offs[None, :]
                    w_mask = gate_mask[:, None] & j_mask[None, :]
                    w_tile = tl.load(weight_hh_ptr + w_offs, mask=w_mask, other=0.0).to(
                        tl.float32
                    )
                    h_tile = tl.load(h_read_base + j_offs, mask=j_mask, other=0.0).to(
                        tl.float32
                    )
                    g_h_acc += tl.sum(w_tile * h_tile[None, :], axis=1)
                if has_bias:
                    g_h_acc += tl.load(
                        bias_hh_ptr + gate_row, mask=gate_mask, other=0.0
                    ).to(tl.float32)

                if gate_idx == 0:
                    r_i_acc, r_h_acc = g_i_acc, g_h_acc
                elif gate_idx == 1:
                    z_i_acc, z_h_acc = g_i_acc, g_h_acc
                else:
                    n_i_acc, n_h_acc = g_i_acc, g_h_acc

            r = tl.sigmoid(r_i_acc + r_h_acc)
            z = tl.sigmoid(z_i_acc + z_h_acc)
            n = tl_extra_shim.tanh(n_i_acc + r * n_h_acc)

            h_prev = tl.load(h_read_base + h_offs, mask=h_mask, other=0.0).to(
                tl.float32
            )
            h_new = (1.0 - z) * n + z * h_prev

            tl.store(output_ptr + t_out_off + h_offs, h_new, mask=h_mask)
            tl.store(h_scratch_base + h_offs, h_new, mask=h_mask)

    for hid_block in range(num_hid_blocks):
        offs = hid_block * BLOCK_SIZE + bid_offs
        mask = offs < hidden_size
        tl.store(
            hy_ptr + batch_idx * hidden_size + offs,
            tl.load(h_scratch_base + offs, mask=mask, other=0.0),
            mask=mask,
        )


# ===================================================================
#  Kernel: GRU  — packed sequences
# ===================================================================


@libentry()
@triton.jit
def _gru_packed_kernel(
    input_ptr,
    hx_ptr,
    weight_ih_ptr,
    weight_hh_ptr,
    bias_ih_ptr,
    bias_hh_ptr,
    output_ptr,
    hy_ptr,
    h_scratch_ptr,
    h_read_ptr,
    batch_sizes_ptr,
    input_offsets_ptr,
    output_offsets_ptr,
    num_steps,
    max_batch,
    input_dim,
    hidden_size,
    has_bias: tl.constexpr,
    reverse: tl.constexpr,
    BLOCK_SIZE: tl.constexpr,
):
    """Single-layer GRU — packed sequences.  Grid: ``(max_batch,)``."""
    pid = tl.program_id(0)
    if pid >= max_batch:
        return

    CHUNK: tl.constexpr = 64
    num_hid_blocks = tl.cdiv(hidden_size, BLOCK_SIZE)
    chunk_offs = tl.arange(0, CHUNK)
    bid_offs = tl.arange(0, BLOCK_SIZE)

    _init_hidden(h_scratch_ptr, hx_ptr, pid, hidden_size, num_hid_blocks, BLOCK_SIZE)

    h_scratch_base = h_scratch_ptr + pid * hidden_size
    h_read_base = h_read_ptr + pid * hidden_size

    for t_loop in range(num_steps):
        t = num_steps - 1 - t_loop if reverse else t_loop
        cur_bs = tl.load(batch_sizes_ptr + t).to(tl.int32)

        inp_offset = tl.load(input_offsets_ptr + t).to(tl.int32)
        out_offset = tl.load(output_offsets_ptr + t).to(tl.int32)
        t_inp_off = inp_offset + pid
        t_out_off = out_offset + pid
        active = pid < cur_bs

        for hid_block in range(num_hid_blocks):
            offs = hid_block * BLOCK_SIZE + bid_offs
            mask = offs < hidden_size
            tl.store(
                h_read_base + offs,
                tl.load(h_scratch_base + offs, mask=mask, other=0.0),
                mask=mask,
            )
        # h_read is read by other warps below; fence the stores first.
        tl.debug_barrier()

        for hid_block in range(num_hid_blocks):
            h_start = hid_block * BLOCK_SIZE
            h_offs = h_start + bid_offs
            h_mask = h_offs < hidden_size

            r_i_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            z_i_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            n_i_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            r_h_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            z_h_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
            n_h_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)

            for gate_idx in tl.static_range(3):
                gate_row = gate_idx * hidden_size + h_start + bid_offs
                gate_mask = (h_start + bid_offs) < hidden_size

                g_i_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
                for inp_start in range(0, input_dim, CHUNK):
                    i_offs = inp_start + chunk_offs
                    i_mask = i_offs < input_dim
                    w_offs = gate_row[:, None] * input_dim + i_offs[None, :]
                    w_mask = gate_mask[:, None] & i_mask[None, :]
                    w_tile = tl.load(weight_ih_ptr + w_offs, mask=w_mask, other=0.0).to(
                        tl.float32
                    )
                    x_tile = tl.load(
                        input_ptr + t_inp_off * input_dim + i_offs,
                        mask=i_mask & active,
                        other=0.0,
                    ).to(tl.float32)
                    g_i_acc += tl.sum(w_tile * x_tile[None, :], axis=1)
                if has_bias:
                    g_i_acc += tl.load(
                        bias_ih_ptr + gate_row, mask=gate_mask, other=0.0
                    ).to(tl.float32)

                g_h_acc = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
                for hid_in_start in range(0, hidden_size, CHUNK):
                    j_offs = hid_in_start + chunk_offs
                    j_mask = j_offs < hidden_size
                    w_offs = gate_row[:, None] * hidden_size + j_offs[None, :]
                    w_mask = gate_mask[:, None] & j_mask[None, :]
                    w_tile = tl.load(weight_hh_ptr + w_offs, mask=w_mask, other=0.0).to(
                        tl.float32
                    )
                    h_tile = tl.load(h_read_base + j_offs, mask=j_mask, other=0.0).to(
                        tl.float32
                    )
                    g_h_acc += tl.sum(w_tile * h_tile[None, :], axis=1)
                if has_bias:
                    g_h_acc += tl.load(
                        bias_hh_ptr + gate_row, mask=gate_mask, other=0.0
                    ).to(tl.float32)

                if gate_idx == 0:
                    r_i_acc, r_h_acc = g_i_acc, g_h_acc
                elif gate_idx == 1:
                    z_i_acc, z_h_acc = g_i_acc, g_h_acc
                else:
                    n_i_acc, n_h_acc = g_i_acc, g_h_acc

            r = tl.sigmoid(r_i_acc + r_h_acc)
            z = tl.sigmoid(z_i_acc + z_h_acc)
            n = tl_extra_shim.tanh(n_i_acc + r * n_h_acc)

            h_prev = tl.load(h_read_base + h_offs, mask=h_mask, other=0.0).to(
                tl.float32
            )
            h_new = (1.0 - z) * n + z * h_prev

            store_mask = h_mask & active
            tl.store(
                output_ptr + t_out_off * hidden_size + h_offs, h_new, mask=store_mask
            )
            old_h = tl.load(h_scratch_base + h_offs, mask=h_mask, other=0.0)
            h_merged = tl.where(active, h_new, old_h)
            tl.store(h_scratch_base + h_offs, h_merged, mask=h_mask)

    for hid_block in range(num_hid_blocks):
        offs = hid_block * BLOCK_SIZE + bid_offs
        mask = offs < hidden_size
        tl.store(
            hy_ptr + pid * hidden_size + offs,
            tl.load(h_scratch_base + offs, mask=mask, other=0.0),
            mask=mask,
        )


# ===================================================================
#  Kernel: dropout  (Triton, element-wise)
# ===================================================================


# ===================================================================
#  Host-side dispatch layer
# ===================================================================


def _compute_offsets(batch_sizes):
    """Return (input_offsets, output_offsets) for packed sequences."""
    inp_offs = [0]
    for bs in batch_sizes:
        inp_offs.append(inp_offs[-1] + bs)
    inp_offs.pop()  # remove last (total_len)
    out_offs = list(inp_offs)  # same layout for output
    return inp_offs, out_offs


def _triton_layer_forward(
    input_seq,
    hx,
    cx,
    w_ih,
    w_hh,
    b_ih,
    b_hh,
    w_hr,
    mode,
    reverse,
    batch_size,
    seq_len,
    input_dim,
    hidden_size,
    proj_size,
    batch_first,
    batch_sizes=None,
):
    """Run one RNN layer+dir using Triton kernels.

    When ``batch_sizes`` is not None, uses the packed variant.
    """
    device = input_seq.device
    dtype = input_seq.dtype
    hidden_out = proj_size if (proj_size > 0 and mode == _LSTM) else hidden_size
    is_packed = batch_sizes is not None
    max_batch = max(batch_sizes) if is_packed else batch_size

    # Reverse input if needed (non-packed only; packed handles reverse in-kernel)
    if reverse and not is_packed:
        input_seq = flip(input_seq, [0]).contiguous()

    # Compute offsets for packed layout
    inp_offs, out_offs = _compute_offsets(batch_sizes) if is_packed else (None, None)

    # Allocate output (use new_empty from input to get real tensors
    # even under flag_gems.use_gems() dispatch)
    if is_packed:
        total_len = input_seq.size(0)
        output = input_seq.new_empty(total_len, hidden_out, dtype=dtype)
    else:
        output = input_seq.new_empty(seq_len, max_batch, hidden_out, dtype=dtype)

    scratch_dim = max(hidden_out, hidden_size) if mode == _LSTM else hidden_out
    h_scratch = input_seq.new_empty(max_batch, scratch_dim, dtype=torch.float32)
    h_read = input_seq.new_empty(max_batch, scratch_dim, dtype=torch.float32)
    # raw hidden state feeding the LSTM projection; only used when proj_size > 0
    h_proj = (
        input_seq.new_empty(max_batch, hidden_size, dtype=torch.float32)
        if (w_hr is not None and mode == _LSTM)
        else input_seq.new_empty(0, dtype=torch.float32)
    )

    hy_out = input_seq.new_empty(max_batch, hidden_out, dtype=dtype)
    cy_out = (
        input_seq.new_empty(max_batch, hidden_size, dtype=dtype)
        if mode == _LSTM
        else None
    )
    c_scratch = (
        input_seq.new_empty(max_batch, hidden_size, dtype=torch.float32)
        if mode == _LSTM
        else None
    )

    grid = (max_batch,)

    has_bias_flag = b_ih is not None
    if not has_bias_flag:
        b_dummy = input_seq.new_empty(0, dtype=torch.float32)
        b_ih_ptr = b_hh_ptr = b_dummy
    else:
        b_ih_ptr = b_ih.contiguous()
        b_hh_ptr = b_hh.contiguous()

    w_hr_ptr = (
        w_hr if (w_hr is not None) else input_seq.new_empty(0, dtype=torch.float32)
    )

    with runtime.torch_device_fn.device(device):
        if is_packed:
            # Packed path
            bs_t = torch.tensor(batch_sizes, dtype=torch.int32, device=device)
            io_t = torch.tensor(inp_offs, dtype=torch.int32, device=device)
            oo_t = torch.tensor(out_offs, dtype=torch.int32, device=device)
            num_steps = len(batch_sizes)

            if mode in (_RNN_RELU, _RNN_TANH):
                nonlinearity = 0 if mode == _RNN_RELU else 1
                _rnn_packed_kernel[grid](
                    input_seq,
                    hx,
                    w_ih,
                    w_hh,
                    b_ih_ptr,
                    b_hh_ptr,
                    output,
                    hy_out,
                    h_scratch,
                    h_read,
                    bs_t,
                    io_t,
                    oo_t,
                    num_steps,
                    max_batch,
                    input_dim,
                    hidden_out,
                    nonlinearity,
                    has_bias_flag,
                    reverse,
                    BLOCK_SIZE=64,
                )
            elif mode == _LSTM:
                _lstm_packed_kernel[grid](
                    input_seq,
                    hx,
                    cx,
                    w_ih,
                    w_hh,
                    w_hr_ptr,
                    b_ih_ptr,
                    b_hh_ptr,
                    output,
                    hy_out,
                    cy_out,
                    h_scratch,
                    h_read,
                    h_proj,
                    c_scratch,
                    bs_t,
                    io_t,
                    oo_t,
                    num_steps,
                    max_batch,
                    input_dim,
                    hidden_size,
                    proj_size,
                    has_bias_flag,
                    w_hr is not None,
                    reverse,
                    BLOCK_SIZE=64,
                )
            elif mode == _GRU:
                _gru_packed_kernel[grid](
                    input_seq,
                    hx,
                    w_ih,
                    w_hh,
                    b_ih_ptr,
                    b_hh_ptr,
                    output,
                    hy_out,
                    h_scratch,
                    h_read,
                    bs_t,
                    io_t,
                    oo_t,
                    num_steps,
                    max_batch,
                    input_dim,
                    hidden_size,
                    has_bias_flag,
                    reverse,
                    BLOCK_SIZE=64,
                )
        else:
            # Uniform batch path
            if mode in (_RNN_RELU, _RNN_TANH):
                nonlinearity = 0 if mode == _RNN_RELU else 1
                _rnn_kernel[grid](
                    input_seq,
                    hx,
                    w_ih,
                    w_hh,
                    b_ih_ptr,
                    b_hh_ptr,
                    output,
                    hy_out,
                    h_scratch,
                    h_read,
                    seq_len,
                    max_batch,
                    input_dim,
                    hidden_out,
                    batch_first,
                    nonlinearity,
                    has_bias_flag,
                    BLOCK_SIZE=64,
                )
            elif mode == _LSTM:
                c_scratch = torch.empty(
                    max_batch, hidden_size, device=device, dtype=torch.float32
                )
                _lstm_kernel[grid](
                    input_seq,
                    hx,
                    cx,
                    w_ih,
                    w_hh,
                    w_hr_ptr,
                    b_ih_ptr,
                    b_hh_ptr,
                    output,
                    hy_out,
                    cy_out,
                    h_scratch,
                    h_read,
                    h_proj,
                    c_scratch,
                    seq_len,
                    max_batch,
                    input_dim,
                    hidden_size,
                    proj_size,
                    batch_first,
                    has_bias_flag,
                    w_hr is not None,
                    BLOCK_SIZE=64,
                )
            elif mode == _GRU:
                _gru_kernel[grid](
                    input_seq,
                    hx,
                    w_ih,
                    w_hh,
                    b_ih_ptr,
                    b_hh_ptr,
                    output,
                    hy_out,
                    h_scratch,
                    h_read,
                    seq_len,
                    max_batch,
                    input_dim,
                    hidden_size,
                    batch_first,
                    has_bias_flag,
                    BLOCK_SIZE=64,
                )

    # Reverse output back if needed (non-packed only; packed handles in-kernel)
    if reverse and not is_packed:
        output = flip(output, [0]).contiguous()

    return output, hy_out, cy_out


# ===================================================================
#  Triton dropout between layers
# ===================================================================


def _triton_dropout(x, p, train):
    """Apply inter-layer dropout with the FlagGems dropout kernel."""
    if p <= 0.0 or not train:
        return x
    out, _ = dropout(x, p, train)
    return out


# ===================================================================
#  Main entry point
# ===================================================================


def _decode_layout(ws, mode):
    if ws == _WS_NB:
        return False, False
    if ws == _WS_B:
        return True, False
    if ws == _WS_NBP:
        if mode != _LSTM:
            raise ValueError("proj only for LSTM")
        return False, True
    if ws == _WS_BP:
        if mode != _LSTM:
            raise ValueError("proj only for LSTM")
        return True, True
    raise ValueError(f"Unsupported weight_stride0: {ws}")


def _build_weight_buf(
    weight, weight_stride0, has_bias, has_proj, num_layers, num_directions
):
    """Flatten ``weight`` into the cuDNN layout.

    The buffer holds every (layer, direction) weight block in order -- w_ih,
    w_hh, and w_hr when projecting -- followed by all bias blocks.
    """
    n_params = weight_stride0
    weight_parts = []
    bias_parts = []
    for layer_idx in range(num_layers):
        for direction_idx in range(num_directions):
            base = (layer_idx * num_directions + direction_idx) * n_params
            weight_parts.append(weight[base])
            weight_parts.append(weight[base + 1])
            if has_proj:
                weight_parts.append(weight[base + (4 if has_bias else 2)])
            if has_bias:
                bias_parts.append(weight[base + 2])
                bias_parts.append(weight[base + 3])
    parts = [t.contiguous().flatten() for t in weight_parts + bias_parts]
    return torch.cat(parts)


def cudnn_rnn(
    input,
    weight,
    weight_stride0,
    weight_buf,
    hx,
    cx,
    mode,
    hidden_size,
    proj_size,
    num_layers,
    batch_first,
    dropout,
    train,
    bidirectional,
    batch_sizes,
    dropout_state,
):
    """Triton-based replacement for ``aten::_cudnn_rnn``.

    All code paths use Triton kernels.

    Returns ``(output, hy, cy, reserve, weight_buf)``.  Two outputs differ from
    the cuDNN ones by design:

    * ``reserve`` is returned empty.  It is the cuDNN backward workspace and is
      kept only because autograd feeds it from the forward into
      ``_cudnn_rnn_backward``; that backward recomputes the recurrence instead
      of consuming the workspace.  A native cuDNN backward cannot read it, so
      forward and backward must run under the same dispatch state.
    * ``weight_buf`` is rebuilt as a flat copy of ``weight`` in the cuDNN
      layout.  It is ignored on input: the weights always come from ``weight``.

    Args:
        dropout_state: Dropout RNG state.  Accepted for aten-API compatibility
            but not consumed: inter-layer dropout draws from the global
            Philox stream, so results are reproducible via ``manual_seed``
            rather than through this tensor.
    """
    logger.debug("GEMS CUDNN_RNN")

    num_directions = 2 if bidirectional else 1
    has_bias, has_proj = _decode_layout(weight_stride0, mode)
    is_packed = bool(batch_sizes)

    # --- Normalize input ---
    if is_packed:
        input_seq = input.contiguous()
        max_batch = max(batch_sizes)
    elif batch_first:
        input_seq = input.transpose(0, 1).contiguous()
        max_batch = input_seq.size(1)
    else:
        input_seq = input.contiguous()
        max_batch = input_seq.size(1)

    # --- Validate ---
    hidden_out = proj_size if has_proj else hidden_size
    expected = (num_layers * num_directions, max_batch, hidden_out)
    if hx.shape != expected:
        raise ValueError(f"hx shape mismatch: {tuple(hx.shape)} vs {expected}")
    cx_given = cx is not None
    if mode == _LSTM:
        expected_c = (num_layers * num_directions, max_batch, hidden_size)
        if cx is None:
            # Absent cx means an all-zero initial cell state.
            cx = input_seq.new_zeros(expected_c, dtype=input.dtype)
        elif cx.shape != expected_c:
            raise ValueError(f"cx shape mismatch: {tuple(cx.shape)} vs {expected_c}")

    # --- Allocate outputs (use new_empty from input to get real tensors
    # even under flag_gems.use_gems() dispatch) ---
    if is_packed:
        output = input_seq.new_empty(
            input_seq.size(0),
            hidden_out * num_directions,
            dtype=input.dtype,
        )
    else:
        seq_len = input_seq.size(0)
        output = input_seq.new_empty(
            seq_len,
            max_batch,
            hidden_out * num_directions,
            dtype=input.dtype,
        )

    hy = input_seq.new_empty(hx.shape, dtype=hx.dtype)
    # cy is only produced for LSTM; other modes return an empty tensor.
    # A caller-supplied cx is empty only when the initial cell state defaults
    # to zeros; cy stays empty in that case too.
    if mode != _LSTM or not cx_given:
        cy = input_seq.new_empty(0, dtype=input.dtype)
    else:
        cy = input_seq.new_empty(cx.shape, dtype=cx.dtype)

    # --- Layer-by-layer ---
    layer_input = input_seq

    for layer_idx in range(num_layers):
        for direction_idx in range(num_directions):
            w_idx = (layer_idx * num_directions + direction_idx) * weight_stride0
            w_ih = weight[w_idx]
            w_hh = weight[w_idx + 1]
            b_ih = weight[w_idx + 2] if has_bias else None
            b_hh = weight[w_idx + 3] if has_bias else None
            w_hr = weight[w_idx + (4 if has_bias else 2)] if has_proj else None

            layer_hx_idx = layer_idx * num_directions + direction_idx
            h = hx[layer_hx_idx]
            c = cx[layer_hx_idx] if mode == _LSTM else None
            rev = direction_idx == 1

            layer_input_dim = (
                weight[0].size(1) if layer_idx == 0 else hidden_out * num_directions
            )

            layer_out, h_out, c_out = _triton_layer_forward(
                layer_input,
                h,
                c,
                w_ih,
                w_hh,
                b_ih,
                b_hh,
                w_hr,
                mode,
                rev,
                max_batch,
                seq_len if not is_packed else 0,
                layer_input_dim,
                hidden_size,
                proj_size,
                False,  # batch_first already normalized
                batch_sizes if is_packed else None,
            )

            out_start = direction_idx * hidden_out
            out_end = out_start + hidden_out
            if is_packed:
                output[:, out_start:out_end] = layer_out
            else:
                output[:, :, out_start:out_end] = layer_out

            hy[layer_hx_idx] = h_out
            if cy.numel() > 0:
                cy[layer_hx_idx] = c_out

        # ---- Dropout between layers (Triton) ----
        # Always clone: the next layer's directions both read the SAME
        # input, but they write to different slices of the output tensor.
        if layer_idx < num_layers - 1:
            layer_input = _triton_dropout(output, dropout, train).clone()

    # --- Finalize layout ---
    if not is_packed and batch_first:
        output = output.transpose(0, 1).contiguous()

    reserve = input_seq.new_empty(0, dtype=torch.uint8)
    weight_buf_out = _build_weight_buf(
        weight, weight_stride0, has_bias, has_proj, num_layers, num_directions
    )
    return output, hy, cy, reserve, weight_buf_out
