# Copyright 2026 FlagOS Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

from .bmm import bmm
from .mm import mm
from .sum import sum_dim

logger = logging.getLogger(__name__)


def _matmul_2d_or_batched(a: torch.Tensor, b: torch.Tensor) -> torch.Tensor:
    """Matrix multiply using the Triton mm/bmm kernels.

    Both ``a`` and ``b`` have their contracting dimension as the last two
    dims (``(..., M, K)`` and ``(..., K, N)``). Leading batch dimensions are
    broadcast against each other, mirroring ``torch.matmul``.
    """
    if a.dim() == 2 and b.dim() == 2:
        return mm(a.contiguous(), b.contiguous())

    M, K = a.shape[-2], a.shape[-1]
    K2, N = b.shape[-2], b.shape[-1]
    batch_shape = torch.broadcast_shapes(a.shape[:-2], b.shape[:-2])

    a_exp = a.expand(*batch_shape, M, K).reshape(-1, M, K).contiguous()
    b_exp = b.expand(*batch_shape, K2, N).reshape(-1, K2, N).contiguous()
    out = bmm(a_exp, b_exp)
    return out.reshape(*batch_shape, M, N)


def _sum_to(grad: torch.Tensor, shape) -> torch.Tensor:
    """Reduce ``grad`` (a broadcasted gradient) back to ``shape`` via summation."""
    shape = tuple(shape)
    while grad.dim() > len(shape):
        grad = sum_dim(grad, dim=[0], keepdim=False)
    for i in range(len(shape)):
        if shape[i] == 1 and grad.shape[i] != 1:
            grad = sum_dim(grad, dim=[i], keepdim=True)
    return grad


def matmul_backward(
    grad: torch.Tensor,
    self: torch.Tensor,
    other: torch.Tensor,
    mask,
):
    """Backward pass for ``torch.matmul``.

    Given ``out = matmul(self, other)`` and the upstream gradient ``grad``,
    returns ``(grad_self, grad_other)``. Each is ``None`` when the
    corresponding entry of ``mask`` is False.
    """
    logger.debug("GEMS MATMUL_BACKWARD")

    need_self, need_other = bool(mask[0]), bool(mask[1])

    dim_self = self.dim()
    dim_other = other.dim()

    # float16/bfloat16 lose too much precision through the chained matmuls and
    # broadcast reductions; compute in float32 and cast the results back.
    compute_dtype = self.dtype
    upcast = self.dtype in (torch.float16, torch.bfloat16)
    if upcast:
        compute_dtype = torch.float32

    s = self.to(compute_dtype) if self.dtype != compute_dtype else self
    o = other.to(compute_dtype) if other.dtype != compute_dtype else other
    g = grad.to(compute_dtype) if grad.dtype != compute_dtype else grad

    # Fold 1D operands up to 2D, mirroring how torch.matmul treats vectors:
    # a 1D `self` becomes (1, K) and a 1D `other` becomes (K, 1). The folded
    # dimensions are dropped from the forward output, so they must be inserted
    # back into `grad` before computing the gradients.
    folded_self = dim_self == 1
    folded_other = dim_other == 1

    if folded_self:
        s = s.unsqueeze(-2)
    if folded_other:
        o = o.unsqueeze(-1)

    if folded_other:
        g = g.unsqueeze(-1)
    if folded_self:
        g = g.unsqueeze(-2)

    grad_self = None
    grad_other = None

    if need_self:
        # grad_self = grad @ other^T
        gs = _matmul_2d_or_batched(g, o.transpose(-2, -1))
        gs = _sum_to(gs, s.shape)
        if folded_self:
            gs = gs.squeeze(-2)
        grad_self = gs.to(self.dtype) if gs.dtype != self.dtype else gs

    if need_other:
        # grad_other = self^T @ grad
        go = _matmul_2d_or_batched(s.transpose(-2, -1), g)
        go = _sum_to(go, o.shape)
        if folded_other:
            go = go.squeeze(-1)
        grad_other = go.to(other.dtype) if go.dtype != other.dtype else go

    return grad_self, grad_other
