# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import triton_lang_extension as ext

logger = logging.getLogger(__name__)


@triton.autotune(
    configs=runtime.get_tuned_config("matrix_power_bmm"),
    key=["M", "N", "K"],
)
@triton.jit
def bmm_kernel(
    A,
    B,
    O,
    M,
    N,
    K,
    stride_ab,
    stride_am,
    stride_ak,
    stride_bb,
    stride_bk,
    stride_bn,
    stride_ob,
    stride_om,
    stride_on,
    TILE_M: tl.constexpr,
    TILE_N: tl.constexpr,
    TILE_K: tl.constexpr,
    IS_FP64: tl.constexpr = False,
):
    pid_b = ext.program_id(2)
    A += pid_b * stride_ab
    B += pid_b * stride_bb
    O += pid_b * stride_ob

    pid_m = ext.program_id(0)
    pid_n = ext.program_id(1)

    offs_m = pid_m * TILE_M + tl.arange(0, TILE_M)
    offs_n = pid_n * TILE_N + tl.arange(0, TILE_N)
    offs_k = tl.arange(0, TILE_K)

    mask_m = offs_m < M
    mask_n = offs_n < N

    a_ptrs = A + offs_m[:, None] * stride_am + offs_k[None, :] * stride_ak
    b_ptrs = B + offs_k[:, None] * stride_bk + offs_n[None, :] * stride_bn
    o_ptrs = O + offs_m[:, None] * stride_om + offs_n[None, :] * stride_on

    num_iters = tl.cdiv(K, TILE_K)
    if IS_FP64:
        o = tl.zeros((TILE_M, TILE_N), dtype=tl.float64)
    else:
        o = tl.zeros((TILE_M, TILE_N), dtype=tl.float32)
    for _ in range(num_iters):
        mask_k = offs_k < K
        mask_a = mask_m[:, None] & mask_k[None, :]
        mask_b = mask_k[:, None] & mask_n[None, :]

        a = tl.load(a_ptrs, mask_a, other=0.0)
        b = tl.load(b_ptrs, mask_b, other=0.0)

        offs_k += TILE_K
        a_ptrs += TILE_K * stride_ak
        b_ptrs += TILE_K * stride_bk

        o += tl.dot(a, b, allow_tf32=False)

    mask_c = mask_m[:, None] & mask_n[None, :]
    tl.store(o_ptrs, o.to(O.dtype.element_ty), mask_c)


def _bmm(A, B):
    """Batched matrix multiply for contiguous 3D tensors of shape (batch, M, K) x (batch, K, N)."""
    batch, M, K = A.shape
    N = B.shape[2]
    out = torch.empty((batch, M, N), dtype=A.dtype, device=A.device)

    grid_fn = lambda meta: (
        triton.cdiv(M, meta["TILE_M"]),
        triton.cdiv(N, meta["TILE_N"]),
        batch,
    )
    with torch_device_fn.device(A.device):
        bmm_kernel[grid_fn](
            A,
            B,
            out,
            M,
            N,
            K,
            A.stride(0),
            A.stride(1),
            A.stride(2),
            B.stride(0),
            B.stride(1),
            B.stride(2),
            out.stride(0),
            out.stride(1),
            out.stride(2),
            IS_FP64=A.dtype == torch.float64,
        )
    return out


def _matrix_power(A, n):
    """Compute A ** n for a batched square matrix using the Triton bmm kernel.

    ``A`` is expected to be a contiguous 3D tensor of shape (batch, M, M).
    """
    batch, M, _ = A.shape

    if n == 0:
        eye = torch.eye(M, dtype=A.dtype, device=A.device)
        return eye.unsqueeze(0).expand(batch, M, M).contiguous()

    if n < 0:
        # A ** (-k) == inv(A) ** k. Matrix inversion has no efficient Triton
        # equivalent here, so obtain the inverse through an LU factorization
        # and a solve against the identity.
        eye = (
            torch.eye(M, dtype=A.dtype, device=A.device)
            .unsqueeze(0)
            .expand(batch, M, M)
            .contiguous()
        )
        lu, pivots = torch.linalg.lu_factor(A)
        A = torch.linalg.lu_solve(lu, pivots, eye).contiguous()
        n = -n

    if n == 1:
        return A.clone()

    # Binary exponentiation (repeated squaring) via batched matmuls.
    result = None
    base = A
    while n > 0:
        if n & 1:
            result = base if result is None else _bmm(result, base)
        n >>= 1
        if n > 0:
            base = _bmm(base, base)
    return result


def matrix_power(A, n):
    logger.debug("GEMS MATRIX_POWER")
    assert A.ndim >= 2, "matrix_power expects a tensor of at least 2 dimensions"
    assert A.shape[-1] == A.shape[-2], "matrix_power expects square matrices"
    assert A.dtype in [
        torch.float16,
        torch.bfloat16,
        torch.float32,
        torch.float64,
    ], f"matrix_power only supports float16, bfloat16, float32, float64, got {A.dtype}"

    M = A.shape[-1]
    batch_shape = A.shape[:-2]
    A3 = A.reshape(-1, M, M).contiguous()

    out = _matrix_power(A3, n)
    return out.reshape(*batch_shape, M, M)


def matrix_power_out(A, n, *, out):
    logger.debug("GEMS MATRIX_POWER_OUT")
    result = matrix_power(A, n)
    out.copy_(result)
    return out
