# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.ops.contiguous import contiguous
from flag_gems.ops.copy import copy_
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def _copy_kernel(inp, out, n_elements, BLOCK_SIZE: tl.constexpr):
    offsets = tl.program_id(0) * BLOCK_SIZE + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements
    tl.store(out + offsets, tl.load(inp + offsets, mask=mask), mask=mask)


@libentry()
@triton.jit
def orgqr_kernel(
    inp,
    tau,
    out,
    M,
    N,
    K,
    input_batch_stride,
    tau_batch_stride,
    out_batch_stride,
    out_row_stride,
    out_col_stride,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    batch = tl.program_id(0)
    col_start = tl.program_id(1) * BLOCK_N
    cols = col_start + tl.arange(0, BLOCK_N)
    rows = tl.arange(0, BLOCK_M)
    row_mask = rows < M
    col_mask = cols < N
    mask = row_mask[:, None] & col_mask[None, :]

    input_base = inp + batch * input_batch_stride
    tau_base = tau + batch * tau_batch_stride
    out_base = out + batch * out_batch_stride
    out_ptrs = (
        out_base + rows[:, None] * out_row_stride + cols[None, :] * out_col_stride
    )

    q = tl.where(rows[:, None] == cols[None, :], 1.0, 0.0).to(inp.dtype.element_ty)
    tl.store(out_ptrs, q, mask=mask)

    for k_idx in range(K - 1, -1, -1):
        tau_k = tl.load(tau_base + k_idx)
        input_col = tl.load(input_base + rows * N + k_idx, mask=row_mask, other=0.0)
        v = tl.where(
            rows > k_idx,
            input_col,
            tl.where(rows == k_idx, 1.0, 0.0),
        )
        q = tl.load(out_ptrs, mask=mask, other=0.0).to(inp.dtype.element_ty)
        dots = tl.sum(v[:, None] * q, axis=0)
        q -= tau_k * v[:, None] * dots[None, :]
        tl.store(out_ptrs, q, mask=mask)


def _validate_orgqr(input, tau, out=None):
    if input.ndim < 2:
        raise RuntimeError("orgqr: input must have at least 2 dimensions")
    if tau.ndim != input.ndim - 1 or tau.shape[:-1] != input.shape[:-2]:
        raise RuntimeError("orgqr: tau batch dimensions must match input")
    if input.shape[-2] < input.shape[-1]:
        raise RuntimeError(
            "orgqr: input.shape[-2] must be greater than or equal to input.shape[-1]"
        )
    if tau.shape[-1] > input.shape[-1]:
        raise RuntimeError(
            "orgqr: input.shape[-1] must be greater than or equal to tau.shape[-1]"
        )
    if input.dtype != tau.dtype or input.device != tau.device:
        raise RuntimeError("orgqr: input and tau must have the same dtype and device")
    if input.is_complex():
        raise RuntimeError(
            "orgqr: complex dtypes are not supported by this Triton kernel"
        )
    if input.dtype not in (torch.float32, torch.float64):
        raise RuntimeError("orgqr: only float32 and float64 inputs are supported")
    if out is not None:
        if out.device != input.device:
            raise RuntimeError("orgqr: input and out must be on the same device")
        if not torch.can_cast(input.dtype, out.dtype):
            raise RuntimeError(
                f"orgqr: result dtype {input.dtype} cannot be safely cast to {out.dtype}"
            )


def _orgqr_impl(input, tau, out):
    _validate_orgqr(input, tau, out)
    if out.shape != input.shape:
        out.resize_(input.shape)

    m, n = input.shape[-2:]
    k = tau.shape[-1]
    batch_size = input.numel() // max(1, m * n)
    if out.numel() == 0:
        return out

    input_work = contiguous(input).view(batch_size, m, n)
    tau_work = contiguous(tau).view(batch_size, k)

    if input_work.data_ptr() == out.data_ptr():
        preserved_input = torch.empty_like(input_work)
        block_size = 1024
        with torch_device_fn.device(input.device):
            _copy_kernel[(triton.cdiv(input.numel(), block_size),)](
                input_work,
                preserved_input,
                input.numel(),
                BLOCK_SIZE=block_size,
            )
        input_work = preserved_input

    copy_back = False
    if out.dtype != input.dtype:
        # Reflectors must be applied in input precision. Cast only the final Q.
        out_work = torch.empty((batch_size, m, n), dtype=input.dtype, device=out.device)
        copy_back = True
    elif input.ndim == 2:
        out_work = out.unsqueeze(0)
    else:
        try:
            out_work = out.view(batch_size, m, n)
        except RuntimeError:
            # Flattening arbitrary batch strides may require a copy. Compute
            # in a workspace and explicitly write back to the provided out.
            out_work = torch.empty(
                (batch_size, m, n), dtype=input.dtype, device=out.device
            )
            copy_back = True

    block_m = triton.next_power_of_2(m)
    block_n = min(triton.next_power_of_2(n), 32)
    with torch_device_fn.device(input.device):
        orgqr_kernel[(batch_size, triton.cdiv(n, block_n))](
            input_work,
            tau_work,
            out_work,
            m,
            n,
            k,
            input_work.stride(0),
            tau_work.stride(0),
            out_work.stride(0),
            out_work.stride(1),
            out_work.stride(2),
            BLOCK_M=block_m,
            BLOCK_N=block_n,
        )
        if copy_back:
            copy_(out, out_work.view(out.shape))
    return out


def orgqr(input, tau):
    """Compute real float32/float64 Q from Householder reflectors.

    Complex inputs are intentionally unsupported by this Triton implementation.
    """
    logger.debug("GEMS ORGQR")
    _validate_orgqr(input, tau)
    out = torch.empty_like(input)
    return _orgqr_impl(input, tau, out)


def orgqr_out(input, tau, *, out):
    """Write Q into ``out``, preserving its storage and arbitrary batch strides."""
    logger.debug("GEMS ORGQR_OUT")
    return _orgqr_impl(input, tau, out)
