# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems import runtime
from flag_gems.runtime import torch_device_fn
from flag_gems.utils import dim_compress, libentry, libtuner
from flag_gems.utils import triton_lang_extension as tle

logger = logging.getLogger(__name__)


@libentry()
@libtuner(
    configs=runtime.get_tuned_config("trapezoid_kernel"),
    key=["M", "N"],
)
@triton.jit
def trapezoid_kernel_dx(
    y_ptr,
    out_ptr,
    M,
    N,
    dx: tl.float64,
    M_STRIDE_Y,
    M_STRIDE_OUT,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    """Trapezoid integration with constant spacing dx."""
    # Accumulate in float64 for float64 inputs, float32 otherwise.
    acc_dtype = tl.float64 if y_ptr.type.element_ty == tl.float64 else tl.float32
    pid_m = tle.program_id(0)

    m_offsets = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    mask_m = m_offsets < M

    acc = tl.zeros((BLOCK_M,), dtype=acc_dtype)

    for n_start in range(0, N - 1, BLOCK_N):
        n_offsets = n_start + tl.arange(0, BLOCK_N)
        mask_n = n_offsets < N - 1

        y_offsets = m_offsets[:, None] * M_STRIDE_Y + n_offsets[None, :]
        mask = mask_m[:, None] & mask_n[None, :]

        y_i = tl.load(y_ptr + y_offsets, mask=mask, other=0.0).to(acc_dtype)
        y_next = tl.load(y_ptr + y_offsets + 1, mask=mask, other=0.0).to(acc_dtype)

        # Trapezoidal rule: (y[i] + y[i+1]) / 2
        trapezoid_sum = (y_i + y_next) * 0.5

        acc += tl.sum(trapezoid_sum, axis=1)

    result = acc * dx
    out_offsets = m_offsets * M_STRIDE_OUT
    tl.store(out_ptr + out_offsets, result, mask=mask_m)


def _normalize_dim(dim, ndim):
    if ndim == 0:
        raise IndexError(f"Dimension specified as {dim} but tensor has no dimensions")
    if not (-ndim <= dim < ndim):
        raise IndexError(
            f"Dimension out of range (expected to be in range of "
            f"[{-ndim}, {ndim - 1}], but got {dim})"
        )
    return dim % ndim


class TrapzOp(torch.autograd.Function):
    """Custom autograd function for the trapezoidal rule.

    The forward pass runs a Triton kernel; the backward pass multiplies the
    upstream gradient by the trapezoidal weights ``dx * [0.5, 1, ..., 1, 0.5]``
    broadcast along the reduced dimension.
    """

    @staticmethod
    def forward(ctx, y, dx, dim):
        logger.debug("GEMS TRAPEZOID_DX")

        dim = _normalize_dim(dim, y.ndim)
        shape = y.shape
        N = shape[dim]
        out_shape = shape[:dim] + shape[dim + 1 :]

        ctx.dx = dx
        ctx.dim = dim
        ctx.N = N
        ctx.y_shape = shape
        ctx.y_dtype = y.dtype

        # Empty tensors or a degenerate reduction dimension (N <= 1) integrate
        # to zero; the reduction dimension is always removed from the shape.
        if y.numel() == 0 or N <= 1:
            return torch.zeros(out_shape, dtype=y.dtype, device=y.device)

        y_compressed = dim_compress(y, dim)
        M = y_compressed.numel() // N

        # Accumulate in float64 for float64 inputs, float32 otherwise; the
        # result is cast back to the input dtype before returning.
        compute_dtype = torch.float64 if y.dtype == torch.float64 else torch.float32
        out_compressed_shape = list(y_compressed.shape)
        out_compressed_shape[-1] = 1
        output = torch.empty(out_compressed_shape, dtype=compute_dtype, device=y.device)

        grid = lambda meta: (triton.cdiv(M, meta["BLOCK_M"]),)  # noqa: E731
        with torch_device_fn.device(y.device):
            trapezoid_kernel_dx[grid](
                y_compressed, output, M, N, dx, N, 1, BLOCK_M=32, BLOCK_N=128
            )

        result = output.reshape(out_shape)
        if compute_dtype != y.dtype:
            result = result.to(y.dtype)
        return result

    @staticmethod
    def backward(ctx, grad_output):
        dx = ctx.dx
        dim = ctx.dim
        N = ctx.N
        y_shape = ctx.y_shape
        y_dtype = ctx.y_dtype

        if N <= 1:
            return (
                torch.zeros(y_shape, dtype=y_dtype, device=grad_output.device),
                None,
                None,
            )

        acc_dtype = torch.float64 if y_dtype == torch.float64 else torch.float32
        w = torch.ones(N, dtype=acc_dtype, device=grad_output.device)
        w[0] = 0.5
        w[-1] = 0.5
        w_shape = [1] * len(y_shape)
        w_shape[dim] = N
        w = w.view(w_shape)

        grad_y = grad_output.to(acc_dtype).unsqueeze(dim) * w * dx
        return grad_y.to(y_dtype), None, None


def trapz(y, dx=1.0, dim=-1):
    """Compute the trapezoidal rule along a dimension with constant spacing.

    Args:
        y: Input tensor.
        dx: Constant spacing between samples.
        dim: Dimension along which to integrate.

    Returns:
        The integral of ``y`` along ``dim``, with the reduced dimension removed.
    """
    if y.dtype == torch.bool:
        raise RuntimeError(
            "trapezoid: received a bool input for `y`, but bool is not supported"
        )

    # Triton kernels are real-valued only, so complex inputs are unsupported.
    # Reject them explicitly instead of silently falling back to native ATen.
    if y.is_complex():
        raise RuntimeError(
            "trapz: complex inputs are not supported by the FlagGems Triton kernel"
        )

    # Integer inputs are promoted to float32, matching PyTorch.
    if not y.is_floating_point():
        y = y.to(torch.float32)

    if isinstance(dx, torch.Tensor):
        dx = dx.item()
    else:
        dx = float(dx)

    return TrapzOp.apply(y, dx, dim)
