# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry, tl_extra_shim
from flag_gems.utils import triton_lang_extension as ext

_pow = tl_extra_shim.pow
logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def vander_complex_kernel(
    xr_ptr,
    xi_ptr,
    outr_ptr,
    outi_ptr,
    M,
    N,
    x_stride,
    increasing: tl.constexpr,
    BLOCK_M: tl.constexpr,
):
    # Complex path: Triton has no native complex type, so the real and imaginary
    # parts are carried separately. Each program handles one row block and walks
    # the columns left-to-right, updating the running power z^k via the complex
    # multiplication (a+bi)(c+di) = (ac-bd) + (ad+bc)i.
    pid = ext.program_id(0)
    rows = pid * BLOCK_M + tl.arange(0, BLOCK_M)
    mask_m = rows < M
    xr = tl.load(xr_ptr + rows * x_stride, mask=mask_m, other=0.0).to(tl.float64)
    xi = tl.load(xi_ptr + rows * x_stride, mask=mask_m, other=0.0).to(tl.float64)

    accr = tl.full([BLOCK_M], 1.0, dtype=tl.float64)
    acci = tl.full([BLOCK_M], 0.0, dtype=tl.float64)
    for k in range(0, N):
        store_col = k if increasing else N - 1 - k
        out_off = rows * N + store_col
        tl.store(outr_ptr + out_off, accr, mask=mask_m)
        tl.store(outi_ptr + out_off, acci, mask=mask_m)
        # accumulator *= x  (complex multiply)
        new_r = accr * xr - acci * xi
        new_i = accr * xi + acci * xr
        accr = new_r
        acci = new_i


@libentry()
@triton.jit
def vander_kernel(
    x_ptr,
    out_ptr,
    M,
    N,
    x_stride,
    increasing: tl.constexpr,
    COMPUTE_DTYPE: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    # Floating-point path: out[i, j] = x[i]^p with p = j (increasing) or N-1-j.
    # Computing in COMPUTE_DTYPE (fp64 for fp64 inputs, otherwise fp32) preserves
    # fp64 precision and lets fp16/bf16 benefit from fp32 accumulation.
    pid_m = ext.program_id(0)
    pid_n = ext.program_id(1)
    rows = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
    cols = pid_n * BLOCK_N + tl.arange(0, BLOCK_N)

    mask_m = rows < M
    x_vals = tl.load(x_ptr + rows * x_stride, mask=mask_m, other=0.0).to(COMPUTE_DTYPE)

    if increasing:
        powers = cols
    else:
        powers = N - 1 - cols
    powers = powers.to(COMPUTE_DTYPE)

    result = _pow(x_vals[:, None], powers[None, :])

    mask_n = cols < N
    mask = mask_m[:, None] & mask_n[None, :]
    out_off = rows[:, None] * N + cols[None, :]
    tl.store(out_ptr + out_off, result, mask=mask)


@libentry()
@triton.jit
def vander_int_kernel(
    x_ptr,
    out_ptr,
    M,
    N,
    x_stride,
    increasing: tl.constexpr,
    BLOCK_M: tl.constexpr,
    BLOCK_N: tl.constexpr,
):
    # Integer path: out[i, j] = x[i]^p computed exactly with int64 cumulative
    # products, matching ATen's cumprod semantics (including wrap-around). Each
    # program sweeps one column tile and carries the running product x^off.
    pid = ext.program_id(0)
    rows = pid * BLOCK_M + tl.arange(0, BLOCK_M)
    mask_m = rows < M
    x_val = tl.load(x_ptr + rows * x_stride, mask=mask_m, other=0).to(tl.int64)

    acc = tl.full([BLOCK_M], 1, dtype=tl.int64)
    for off in range(0, N, BLOCK_N):
        k = off + tl.arange(0, BLOCK_N)
        col_mask = k < N
        local = tl.arange(0, BLOCK_N)
        # Seed the tile with [1, x, x, ..., x] so a cumulative product yields the
        # local powers [1, x, x^2, ..., x^(BLOCK_N-1)].
        seed = tl.where(local[None, :] == 0, 1, x_val[:, None])
        powers = tl.cumprod(seed, axis=1)
        block = acc[:, None] * powers
        if increasing:
            store_col = k
        else:
            store_col = N - 1 - k
        out_off = rows[:, None] * N + store_col[None, :]
        mask = mask_m[:, None] & col_mask[None, :]
        tl.store(out_ptr + out_off, block, mask=mask)
        # Advance the running product by one tile: x^(off + BLOCK_N).
        last_col = tl.arange(0, BLOCK_N) == (BLOCK_N - 1)
        last_local = tl.sum(tl.where(last_col[None, :], powers, 0), axis=1)
        acc = acc * last_local * x_val


def vander(x, N=None, increasing=False):
    logger.debug("GEMS VANDER")

    if x.ndim != 1:
        raise RuntimeError("x must be a one-dimensional tensor.")

    if N is not None and N < 0:
        raise RuntimeError("N must be non-negative.")

    M = x.shape[0]
    if N is None:
        N = M

    if x.is_complex():
        # ATen keeps the complex dtype; compute real/imag powers separately.
        out = torch.empty((M, N), dtype=x.dtype, device=x.device)
        if M == 0 or N == 0:
            return out
        xc = x.contiguous()
        xr = xc.real.contiguous()
        xi = xc.imag.contiguous()
        outr = torch.empty((M, N), dtype=xr.dtype, device=x.device)
        outi = torch.empty((M, N), dtype=xr.dtype, device=x.device)
        BLOCK_M = 32
        grid = (triton.cdiv(M, BLOCK_M),)
        vander_complex_kernel[grid](
            xr,
            xi,
            outr,
            outi,
            M,
            N,
            xr.stride(0),
            increasing=increasing,
            BLOCK_M=BLOCK_M,
        )
        out.real.copy_(outr)
        out.imag.copy_(outi)
        return out

    # ATen promotes the input with long: bool/integer -> int64, while
    # floating-point dtypes keep their own type.
    out_dtype = torch.promote_types(x.dtype, torch.long)
    out = torch.empty((M, N), dtype=out_dtype, device=x.device)

    if M == 0 or N == 0:
        return out

    x_stride = x.stride(0)

    BLOCK_M = 32
    BLOCK_N = 32
    if x.is_floating_point():
        compute_dtype = tl.float64 if x.dtype == torch.float64 else tl.float32
        grid = (triton.cdiv(M, BLOCK_M), triton.cdiv(N, BLOCK_N))
        vander_kernel[grid](
            x,
            out,
            M,
            N,
            x_stride,
            increasing=increasing,
            COMPUTE_DTYPE=compute_dtype,
            BLOCK_M=BLOCK_M,
            BLOCK_N=BLOCK_N,
        )
    else:
        grid = (triton.cdiv(M, BLOCK_M),)
        vander_int_kernel[grid](
            x,
            out,
            M,
            N,
            x_stride,
            increasing=increasing,
            BLOCK_M=BLOCK_M,
            BLOCK_N=BLOCK_N,
        )
    return out
