# Note this *workflow_run* workflow runs on the default branch.
name: coverage

on:
  workflow_run:
    workflows:
      - daily
    types:
      - completed
jobs:
  publish-coverage:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          ref: gh-pages

      - id: download-coverage-data
        uses: actions/github-script@v8
        with:
          result-encoding: string
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "op-ut-coverage"
            })[0];

            // There could be a case that no coverage data were generated.
            if (matchArtifact === undefined) {
              return "NO_DATA";
            } else {
              let download = await github.rest.actions.downloadArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: matchArtifact.id,
                 archive_format: 'zip',
              });
              const fs = require('fs');
              const path = require('path');
              const temp = '${{ runner.temp }}/artifacts';
              if (!fs.existsSync(temp)){
                fs.mkdirSync(temp);
              }
              fs.writeFileSync(path.join(temp, 'op-ut-coverage.zip'), Buffer.from(download.data));
              return "HAS_DATA";
            }

      - id: nnzip-artifact
        if: steps.download-coverage-data.outputs.result == "HAS_DATA"
        run: unzip "${{ runner.temp }}/artifacts/op-ut-coverage.zip" -d "${{ runner.temp }}/artifacts"

      - id: prepare-changes
        if: steps.download-coverage-data.outputs.result == "HAS_DATA"
        shell: bash
        run: |
          COV_ID=$(cat ${{ runner.temp }}/artifacts/COVERAGE_ID)
          echo "COV_ID=${COV_ID}" > $GITHUB_ENV
          DATE=${COV_ID:0:8}

          rm -fr docs/coverage/${COV_ID}*
          mkdir -p docs/coverage/${COV_ID}
          mv ${{ runner.temp }}/artifacts/htmlcov/* docs/coverage/${COV_ID}/

          mkdir -p docs/test/unit/${COV_ID}
          mv ${{ runner.temp }}/artifacts/${COV_ID}-summary.md docs/test/unit/${COV_ID}/ut-summary.md

      - id: commit-change
        if: steps.download-coverage-data.outputs.result == "HAS_DATA"
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs
          git commit -a -m "Add coverage data for ${COV_ID}"

      - id: push-change
        if: steps.download-coverage-data.outputs.result == "HAS_DATA"
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
